'use client';
import {useRef,useState,useEffect} from 'react';
import {ArrowLeft,ImagePlus,Upload,Check,Send} from 'lucide-react';
import {Shell,api} from '../community';
import {readBlocks,renderBlocks,insertFragment,parsePaste,type Block} from '@/lib/editor';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
export default function Composer(){const editor=useRef<HTMLDivElement>(null);const file=useRef<HTMLInputElement>(null);const [title,setTitle]=useState(''),[nickname,setNickname]=useState(''),[category,setCategory]=useState('유머'),[source,setSource]=useState('');const [busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[editId,setEditId]=useState(''),[signedIn,setSignedIn]=useState<boolean|null>(null),[ready,setReady]=useState(false);const dirty=useRef(false),uploadLock=useRef(false),saved=useRef(false);
useEffect(()=>{api('/api/me').then(d=>setSignedIn(d.signedIn)).catch(()=>setSignedIn(false));const id=new URLSearchParams(location.search).get('edit');if(id){setEditId(id);api('/api/posts/'+id).then(d=>{if(!d.post.mine)throw new Error('본인 글만 수정할 수 있습니다.');setTitle(d.post.title);setNickname(d.post.nickname);setCategory(d.post.category);setSource(d.post.source||'');if(editor.current)renderBlocks(editor.current,JSON.parse(d.post.body||'[]'));setReady(true)}).catch(e=>setError(e.message))}else{try{const draft=JSON.parse(localStorage.getItem('secretagit-draft')||'null');if(draft){setTitle(draft.title||'');setNickname(draft.nickname||'');setCategory(draft.category||'유머');setSource(draft.source||'');if(editor.current)renderBlocks(editor.current,draft.blocks||[]);setStatus('이 기기에 저장된 임시 글을 복원했어요.')}}catch{}setReady(true)}const stop=(e:BeforeUnloadEvent)=>{if(dirty.current&&!saved.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop)},[]);
useEffect(()=>{if(!ready||editId)return;const timer=setInterval(()=>{if(!editor.current||saved.current)return;try{localStorage.setItem('secretagit-draft',JSON.stringify({title,nickname,category,source,blocks:readBlocks(editor.current)}))}catch{}},2000);return()=>clearInterval(timer)},[title,nickname,category,source,ready,editId]);
async function upload(node:HTMLElement,value:File|string){try{let payload:BodyInit,headers:Record<string,string>;if(typeof value==='string'){if(value.startsWith('data:image/')){if(value.length>14000000)throw new Error('이미지는 10MB까지 지원합니다.');const r=await fetch(value);payload=await r.blob();headers={'Content-Type':'application/octet-stream'}}else{payload=JSON.stringify({url:value.startsWith('//')?'https:'+value:value});headers={'Content-Type':'application/json'}}}else{if(value.size>10*1024*1024)throw new Error('이미지는 10MB까지 지원합니다.');payload=value;headers={'Content-Type':'application/octet-stream'}}const data=await api('/api/media',{method:'POST',headers,body:payload});const img=document.createElement('img');img.src=data.url;img.dataset.mediaId=data.id;img.alt='첨부 이미지';node.replaceWith(img);dirty.current=true}catch(e){node.dataset.status='error';node.textContent=(e as Error).message+' ';const retry=document.createElement('button');retry.type='button';retry.textContent='재시도';retry.onclick=()=>run([{node,value}]);const remove=document.createElement('button');remove.type='button';remove.textContent='빼기';remove.onclick=()=>{node.remove();dirty.current=true};node.appendChild(retry);node.appendChild(remove)}}
async function run(items:{node:HTMLElement;value:File|string}[]){if(uploadLock.current){setError('현재 이미지 저장이 끝나면 다시 붙여넣어 주세요.');return}uploadLock.current=true;setUploading(true);setError('');try{for(const item of items){if(!item.node.isConnected)continue;item.node.dataset.status='pending';item.node.textContent='이미지를 저장하고 있어요…';await upload(item.node,item.value)}setStatus('이미지 처리가 끝났어요. 실패 표시가 있는지 확인해 주세요.')}finally{uploadLock.current=false;setUploading(false)}}
function files(items:File[]){if(!editor.current||uploadLock.current)return;const current=editor.current.querySelectorAll('img,[data-status]').length;if(current+items.length>20){setError('사진은 최대 20장까지 첨부할 수 있어요.');return}const frag=document.createDocumentFragment();const tasks=items.map(value=>{const node=document.createElement('span');node.className='failed-media';node.style.display='block';node.contentEditable='false';node.dataset.status='pending';node.textContent='이미지 저장 준비 중…';frag.append(node);return {node,value}});insertFragment(editor.current,frag);void run(tasks)}
async function submit(){setError('');if(!editor.current||!ready)return;if(!signedIn){setError('로그인 후 등록해 주세요.');return}if(!title.trim()||!nickname.trim()){setError('제목과 닉네임을 입력해 주세요.');return}if(editor.current.querySelector('[data-status]')){setError('아직 저장되지 않은 이미지가 있어요. 재시도하거나 빼고 등록해 주세요.');return}const blocks=readBlocks(editor.current);if(!blocks.length){setError('본문이나 사진을 넣어 주세요.');return}setBusy(true);try{const d=await api(editId?'/api/posts/'+editId:'/api/posts',{method:editId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,nickname,category,source,blocks})});saved.current=true;if(!editId){try{localStorage.removeItem('secretagit-draft')}catch{}}location.href='/post/'+d.id}catch(e){setError((e as Error).message);setBusy(false)}}
useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!ctx)return;const life=new AbortController();try{void Promise.resolve(ctx.registerTool({name:'stage_community_draft',description:'제목과 본문을 편집기에 준비합니다. 게시하지 않습니다.',inputSchema:{type:'object',properties:{title:{type:'string'},text:{type:'string'}},required:['title','text'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const d=input as {title?:unknown;text?:unknown};if(typeof d.title!=='string'||d.title.length>120||typeof d.text!=='string'||d.text.length>30000)throw new Error('Invalid draft');if(!editor.current||uploadLock.current)throw new Error('Editor busy');setTitle(d.title);renderBlocks(editor.current,[{type:'text',text:d.text}]);dirty.current=true;return {staged:true,published:false}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
return <Shell><a className="back" href="/"><ArrowLeft/>이야기 목록</a><div className="panel"><h1>{editId?'이야기 수정':'이야기 쓰기'}</h1><p className="subtext">오늘의 웃음을 같이 나눠요.</p>{signedIn===false&&<div className="status">등록과 이미지 저장은 로그인이 필요해요. <a style={{textDecoration:'underline'}} href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/write'+(editId?'?edit='+editId:''))} target="_top">ChatGPT로 로그인</a></div>}<div className="field"><label>게시판</label><RadioGroup value={category} onValueChange={v=>{setCategory(v);dirty.current=true}} className="flex flex-wrap gap-4">{['유머','짤','이슈','자유'].map(b=><label key={b} className="flex items-center gap-2" style={{margin:0,fontWeight:400}}><RadioGroupItem value={b}/>{b}</label>)}</RadioGroup></div><input className="field-input title-input" aria-label="제목" placeholder="제목을 입력해 주세요" maxLength={120} value={title} onChange={e=>{setTitle(e.target.value);dirty.current=true}}/><div className="editor-toolbar"><button className="secondary" type="button" disabled={uploading||!signedIn||!ready} onClick={()=>file.current?.click()}><ImagePlus/>사진 첨부</button><small>붙여넣기 · 드래그 & 드롭 / 20장, 한 장 10MB</small><input ref={file} hidden type="file" accept="image/jpeg,image/png,image/gif,image/webp,image/avif" multiple onChange={e=>{files(Array.from(e.target.files||[]));e.target.value=''}}/></div><div ref={editor} className="editor" contentEditable={!busy&&ready} suppressContentEditableWarning role="textbox" aria-label="본문" aria-multiline="true" data-placeholder="여기에 이야기를 적거나, 글과 이미지를 붙여넣어 주세요." onInput={()=>dirty.current=true} onPaste={e=>{e.preventDefault();if(!editor.current||uploadLock.current){setError('이미지 저장이 끝나면 다시 붙여넣어 주세요.');return}const html=e.clipboardData.getData('text/html');if(!html&&e.clipboardData.files.length){files(Array.from(e.clipboardData.files));return}const parsed=parsePaste(html,e.clipboardData.getData('text/plain'));if(editor.current.querySelectorAll('img,[data-status]').length+parsed.pending.length>20){setError('사진은 최대 20장까지 첨부할 수 있어요.');return}insertFragment(editor.current,parsed.fragment);dirty.current=true;if(parsed.pending.length)void run(parsed.pending.map(p=>({node:p.node,value:p.url})))}}
onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();files(Array.from(e.dataTransfer.files))}}/><div className="field"><label htmlFor="nickname">닉네임</label><input id="nickname" className="field-input" placeholder="이 글에 표시할 이름" maxLength={24} value={nickname} onChange={e=>{setNickname(e.target.value);dirty.current=true}}/></div><div className="field"><label htmlFor="source">출처 <span style={{fontWeight:400,color:'#9698aa'}}>선택</span></label><input id="source" className="field-input" type="url" placeholder="원본 게시글 주소 https://…" value={source} onChange={e=>{setSource(e.target.value);dirty.current=true}}/></div>{uploading&&<p className="status" role="status"><Upload style={{display:'inline'}}/> 이미지 저장 중…</p>}{status&&!uploading&&<p className="status" role="status"><Check style={{display:'inline'}}/> {status}</p>}{error&&<p className="status error" role="alert">{error}</p>}<div className="form-actions"><p className="subtext" style={{margin:0}}>공유할 수 있는 콘텐츠만 올려 주세요.<br/>{editId?'수정 내용은 등록 시 반영돼요.':'작성 중인 글은 이 기기에 임시 저장돼요.'}</p><button className="primary" disabled={busy||uploading||!ready} onClick={submit}><Send/>{busy?'등록 중…':editId?'수정 완료':'등록하기'}</button></div></div></Shell>}




