import {adminSourceInfo} from '@/lib/admin-provenance';
import {settings,member,ensureMember,isAdmin} from '@/lib/settings';
import {wrap,db,guard,json,cleanText,content,sourceUrl,HttpError} from '@/lib/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {userPostBoards,snsTopics} from '@/lib/board-label';
import {normalizeStoredEconomyPost} from '@/lib/automation/mail-normalize';
function id(req:Request){return new URL(req.url).pathname.split('/').pop()!}
export const GET=wrap(async req=>{const postId=id(req),u=await getChatGPTUser();const p=await db().prepare('SELECT p.*,(SELECT COUNT(*) FROM likes WHERE post_id=p.id) AS likes,(SELECT COUNT(*) FROM comments WHERE post_id=p.id) AS comments FROM posts p WHERE p.id=? AND p.hidden=0').bind(postId).first();if(!p)throw new HttpError(404,'삭제되었거나 없는 글입니다.');const [comments,likedRow,settingResult,account,purchases,sources,previous,next]=await Promise.all([db().prepare('SELECT id,owner,nickname,body,created_at,origin FROM comments WHERE post_id=? ORDER BY created_at LIMIT 300').bind(postId).all(),u?db().prepare('SELECT 1 liked FROM likes WHERE post_id=? AND owner=?').bind(postId,u.userId).first():null,settings(),u?member(u.userId):null,u?db().prepare('SELECT media_id FROM purchases WHERE owner=? AND post_id=?').bind(u.userId,postId).all():null,adminSourceInfo([String(p.id)]),db().prepare('SELECT id,title FROM posts WHERE hidden=0 AND category=? AND created_at<? ORDER BY created_at DESC LIMIT 1').bind(p.category,p.created_at).first(),db().prepare('SELECT id,title FROM posts WHERE hidden=0 AND category=? AND created_at>? ORDER BY created_at ASC LIMIT 1').bind(p.category,p.created_at).first()]);const {owner,...safe}=p;if(safe.category==='경제')Object.assign(safe,normalizeStoredEconomyPost(String(safe.title||''),String(safe.body||'[]')));if(p.system_author==='system:auto')safe.nickname=p.category==='스르륵 유머'?'스르륵':'꿀잼픽';else if(p.system_author){const profile=await db().prepare('SELECT display_name FROM system_profiles WHERE id=?').bind(p.system_author).first();if(profile)safe.nickname=profile.display_name;}if(sources[String(p.id)]){safe.adminSourceName=sources[String(p.id)].name;if(sources[String(p.id)].url)safe.adminSourceUrl=sources[String(p.id)].url;}delete safe.source_candidate;delete safe.system_author;delete safe.text;return Response.json({settings:settingResult.settings,member:account,signedIn:!!u,purchased:(purchases?.results||[]).map(x=>x.media_id||'text'),post:{...safe,mine:owner===u?.userId,liked:!!likedRow},comments:comments.results.map(({owner,...c})=>({...c,mine:owner===u?.userId})),neighbors:{previous,next}},{headers:{'Cache-Control':'private, no-store'}})});
export const PUT=wrap(async req=>{const u=await guard(req);const d=await json(req);const admin=isAdmin(u);const p=await db().prepare('SELECT id,owner,nickname,category,topic FROM posts WHERE id=? AND hidden=0'+(admin?'':' AND owner=?')).bind(...(admin?[id(req)]:[id(req),u.userId])).first<{id:string;owner:string;nickname:string;category:string;topic:string}>();if(!p)throw new HttpError(403,'본인 글만 수정할 수 있습니다.');const others=p.owner!==u.userId;/* Admins may edit posts owned by other accounts (collected posts) without taking them over. */if(!(others&&d.category===p.category)&&!userPostBoards.includes(d.category))throw new HttpError(400,d.category==='경제'?'경제속보는 자동 수집 전용 게시판입니다.':'게시판을 다시 선택해 주세요.');const category=d.category,topic=others&&category===p.category?(p.topic||''):category==='SNS'&&snsTopics.includes(d.topic)?d.topic:'',nickname=others?p.nickname:(await ensureMember(u.userId)).nickname;const blocks=await content(d.blocks,[u.userId,p.owner]);const image=blocks.find(b=>b.type==='image');await db().prepare('UPDATE posts SET title=?,nickname=?,category=?,topic=?,body=?,source=?,thumbnail=? WHERE id=? AND hidden=0').bind(cleanText(d.title,120),nickname,category,topic,JSON.stringify(blocks),sourceUrl(d.source),image?'/api/media/'+image.id:'',id(req)).run();return Response.json({id:id(req)})});
export const DELETE=wrap(async req=>{const u=await guard(req);const d=await json(req);if(d.confirm!=='삭제')throw new HttpError(400,'삭제를 입력해 주세요.');const r=await db().prepare('UPDATE posts SET hidden=1,deleted_at=? WHERE id=? AND owner=? AND hidden=0').bind(Date.now(),id(req),u.userId).run();if(!r.meta.changes)throw new HttpError(403,'본인 글만 삭제할 수 있습니다.');return Response.json({ok:true})});


