import {adminSourceNames} from '@/lib/admin-provenance';
import {settings,member} from '@/lib/settings';
import {wrap,db,guard,json,cleanText,content,sourceUrl,HttpError} from '@/lib/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
function id(req:Request){return new URL(req.url).pathname.split('/').pop()!}
export const GET=wrap(async req=>{const u=await getChatGPTUser();const p=await db().prepare('SELECT p.*,(SELECT COUNT(*) FROM likes WHERE post_id=p.id) AS likes,(SELECT COUNT(*) FROM comments WHERE post_id=p.id) AS comments FROM posts p WHERE p.id=? AND p.hidden=0').bind(id(req)).first();if(!p)throw new HttpError(404,'삭제되었거나 없는 글입니다.');const comments=await db().prepare('SELECT id,owner,nickname,body,created_at,origin FROM comments WHERE post_id=? ORDER BY created_at LIMIT 300').bind(id(req)).all();const liked=u?!!await db().prepare('SELECT 1 FROM likes WHERE post_id=? AND owner=?').bind(id(req),u.userId).first():false;const {owner,...safe}=p;if(p.system_author==='system:auto')safe.nickname='꿀잼픽';else if(p.system_author){const profile=await db().prepare('SELECT display_name FROM system_profiles WHERE id=?').bind(p.system_author).first();if(profile)safe.nickname=profile.display_name;}const sources=await adminSourceNames([String(p.id)]);if(sources[String(p.id)])safe.adminSourceName=sources[String(p.id)];delete safe.source_candidate;delete safe.system_author;const config=(await settings()).settings;const account=u?await member(u.userId):null;const purchases=u?(await db().prepare('SELECT media_id FROM purchases WHERE owner=? AND post_id=?').bind(u.userId,id(req)).all()).results:[];return Response.json({settings:config,member:account,signedIn:!!u,purchased:purchases.map(x=>x.media_id||'text'),post:{...safe,mine:owner===u?.userId,liked},comments:comments.results.map(({owner,...c})=>({...c,mine:owner===u?.userId}))},{headers:{'Cache-Control':'private, no-store'}})});
export const PUT=wrap(async req=>{const u=await guard(req);const d=await json(req);const p=await db().prepare('SELECT id FROM posts WHERE id=? AND owner=? AND hidden=0').bind(id(req),u.userId).first();if(!p)throw new HttpError(403,'본인 글만 수정할 수 있습니다.');const blocks=await content(d.blocks,u.userId);const image=blocks.find(b=>b.type==='image');await db().prepare('UPDATE posts SET title=?,nickname=?,category=?,body=?,source=?,thumbnail=? WHERE id=? AND owner=? AND hidden=0').bind(cleanText(d.title,120),cleanText(d.nickname,24),['유머','짤','영상','이슈','자유','경제'].includes(d.category)?d.category:'자유',JSON.stringify(blocks),sourceUrl(d.source),image?'/api/media/'+image.id:'',id(req),u.userId).run();return Response.json({id:id(req)})});
export const DELETE=wrap(async req=>{const u=await guard(req);const d=await json(req);if(d.confirm!=='삭제')throw new HttpError(400,'삭제를 입력해 주세요.');const r=await db().prepare('UPDATE posts SET hidden=1 WHERE id=? AND owner=? AND hidden=0').bind(id(req),u.userId).run();if(!r.meta.changes)throw new HttpError(403,'본인 글만 삭제할 수 있습니다.');return Response.json({ok:true})});


