import {MODE_LABELS,requiredFields} from '@/lib/automation/modes.mjs';
type Row=Record<string,unknown>;
const names:Record<string,string>={title:'제목',sourceUrl:'원문 URL',sourcePostId:'글 ID',body:'본문·요약',image:'이미지',thumbnail:'썸네일',video:'영상',comments:'댓글',views:'조회수',recommends:'추천수',author:'작성자',createdAt:'작성 시각'};
export function ModeStatus({row}:{row:Row}){let source:Row={},v:Row={};try{source=JSON.parse(String(row.config||'{}'));v=JSON.parse(String(row.validation_counts||'{}')).validation||{}}catch{}
 const mode=String(v.version===3?v.mode:source.resolvedMode||source.collectionMode||'AUTO'),stages=(v.stages||{}) as Record<string,Row>,fields=(v.availableFields||[]) as string[],missing=(v.missingFields||[]) as string[];
 return <div className="ops-mode-status"><strong>수집 방식: {MODE_LABELS[mode as keyof typeof MODE_LABELS]||mode} ({mode})</strong><p>설정: {String(source.collectionMode||'AUTO')} · 필수: {requiredFields(source).map((f:string)=>names[f]||f).join(', ')}</p>
 {v.version===3?<><div className="ops-mode-stages">{Object.entries({list:'목록',detail:'상세',comments:'댓글',media:'미디어'}).map(([key,label])=>{const stage=stages[key]||{};return <span key={key}>{label}: {stage.status==='passed'?'성공':stage.status==='unused'?'사용 안 함':stage.status==='failed'?'실패':stage.status==='empty'?'확보 안 됨':'미실행'}{key==='list'?' '+String(v.listCount||0)+'개':''}{key==='media'&&stage.origin==='list'?' · 목록에서 추출':''}</span>})}</div><p>확보: {fields.length?fields.map(f=>names[f]||f).join(', '):'없음'}<br/>부족: {missing.length?missing.map(f=>names[f]||f).join(', '):'없음'}<br/>최종: {row.can_enable?'ON 가능':'현재 설정으로 ON 불가'}</p>{Array.isArray(v.warnings)&&v.warnings.length>0&&<details><summary>선택 항목·일부 글 처리 기록</summary><pre>{(v.warnings as string[]).join('\n')}</pre></details>}{!row.can_enable&&Array.isArray(v.alternatives)&&v.alternatives.length>0&&<p>대안: 목록에서 제목·원문 링크는 확보됐습니다. 원문 링크 모음 모드로 바꾸고 필수를 제목·URL·ID로 설정하면 별도 검사할 수 있습니다. 본문·이미지 확보를 대신하지는 않습니다.</p>}</>:<p>기존 검증 기록입니다. 다음 수집 테스트부터 단계별 판별 결과가 표시됩니다.</p>}
 </div>
}
