import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {sourceSchema} from '../lib/automation/config.ts';
const base=process.env.QA_BASE||'http://127.0.0.1:8787',token=JSON.parse(readFileSync(process.env.QA_CONFIG||'.sites-runtime/v3-qa-config.json')).vars.WORKER_TOKEN,run=Date.now().toString(36);const admin={'oai-authenticated-user-id':'v3-admin','oai-authenticated-user-email':'seedy@sites.test',origin:base};
async function req(route,body,headers=admin,status=200){const r=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{...headers,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,status,JSON.stringify({route,d}));return d}const op=(action,body={},status=200)=>req('/api/ops',{action,...body},admin,status),rpc=(action,body={},status=200)=>req('/api/worker',{action,...body},{Authorization:'Bearer '+token},status),snapshot=()=>req('/api/ops');const results=[];
await req('/api/ops',undefined,{},403);await req('/api/worker',{action:'claim'},{Authorization:'Bearer invalid'},401);results.push('admin and worker authentication');
let data=await snapshot();await op('settings',{revision:data.revision,config:{...data.config,paused:true}});const id='fixture-'+run,s=sourceSchema.parse({id,name:'검증 소스',url:'https://example.com/best',dailyLimit:1});await op('source',{source:{...s,enabled:true}},409);await op('source',{source:s});await op('scan',{id,test:true});let {task}=await rpc('claim',{workerId:'qa-worker'});assert.equal(task.kind,'scan');const item={externalId:'first',url:'https://example.com/post/first',title:'새로운 웃음 '+run,publishedAt:Date.now(),metrics:{views:100,likes:10,comments:7},blocks:[{type:'text',text:'일반적인 유머 이야기 본문입니다. 오늘도 함께 웃어요. '+run}],comments:[{id:'c',text:'재밌네요'}],mediaHash:''};await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[item]}});await op('source',{source:{...s,enabled:true}});data=await snapshot();assert(data.sources.find(x=>x.id===id).tested_at);results.push('test scan while paused, validation gate');
await op('settings',{revision:data.revision,config:{...data.config,paused:false,gmailEnabled:true,gmailMailbox:'dedicated@example.com',gmailSenders:['news@example.com']}});await op('schedule');data=await snapshot();let job=data.jobs.find(x=>x.source_id===id);assert(job);await op('schedule');assert.equal((await snapshot()).jobs.filter(x=>x.source_id===id).length,1);await op('publishNow',{id:job.id});for(let i=0;i<5;i++){({task}=await rpc('claim',{workerId:'qa-worker'}));if(task?.kind==='publish')break;if(task)await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[]}})}assert.equal(task.kind,'publish');await rpc('complete',{id:task.id,token:task.lease_token,result:{blocks:item.blocks,warnings:[]}});const post=await req('/api/posts/'+job.id);assert.equal(post.post.title,item.title);assert.equal(post.comments.length,1);assert.equal(post.post.source_candidate,undefined);results.push('daily cap, scheduled publication, imported comments, private provenance');
await op('scan',{id,test:true});({task}=await rpc('claim',{workerId:'qa-worker'}));while(task.kind!=='scan'){await rpc('complete',{id:task.id,token:task.lease_token,result:{}});({task}=await rpc('claim',{workerId:'qa-worker'}))}await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[item,{...item,externalId:'dup',url:'https://example.com/post/dup'}]}});data=await snapshot();assert(data.candidates.some(x=>x.external_id==='dup'&&x.status==='duplicate'));results.push('repeated scan and cross-candidate hash dedup');
await op('gmail');({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.kind,'gmail');const auth={id:task.id,token:task.lease_token};const mail={providerId:'m'+run,messageId:'message'+run,sender:'news@example.com',subject:'경제 동향 '+run,body:'오늘 경제 지표와 시장 분위기를 요약합니다. '+run,receivedAt:Date.now(),labels:['AUTO_POST'],mailbox:'dedicated@example.com'};const safe=await rpc('mail',{...auth,message:mail});assert.equal(safe.status,'published');const dup=await rpc('mail',{...auth,message:mail});assert(dup.duplicate);const pii=await rpc('mail',{...auth,message:{...mail,providerId:'p'+run,messageId:'pii'+run,body:'연락처 private@example.com '+run}});assert.equal(pii.status,'review_required');await rpc('mail',{...auth,message:{...mail,mailbox:'personal@example.com'}},403);await op('mailApprove',{id:pii.id,title:'경제 요약',body:'개인정보를 제거한 경제 요약입니다. '+run});await rpc('complete',{...auth,result:{}});const economy=await req('/api/posts?board='+encodeURIComponent('경제'));assert(economy.posts.some(x=>x.id===safe.id));results.push('Gmail dedicated mailbox, privacy hold, edit approval, dedup, economy feed');
const short=await op('shortCreate',{postIds:[job.id],config:{autoCombine:false}});await op('shortCreate',{postIds:[job.id],config:{autoCombine:false}},409);({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.kind,'render');await rpc('heartbeat',{id:task.id,token:task.lease_token});await op('shortApprove',{id:short.id},409);await op('shortCancel',{id:short.id});await rpc('heartbeat',{id:task.id,token:task.lease_token},409);results.push('shorts duplicate lock, heartbeat, QC approval gate, cancellation');
// Leave this isolated QA environment paused after assertions.
data=await snapshot();await op('settings',{revision:data.revision,config:{...data.config,paused:true}});writeFileSync('test-results/automation-api.json',JSON.stringify({passed:true,at:new Date().toISOString(),results},null,2));console.log('PASS:',results.join('; '));
