import {sourceIdentity} from '../lib/automation/validation.mjs';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {sourceSchema} from '../lib/automation/config.ts';
const base=process.env.QA_BASE||'http://127.0.0.1:8787',token=JSON.parse(readFileSync(process.env.QA_CONFIG||'.sites-runtime/v3-qa-config.json')).vars.WORKER_TOKEN,run=Date.now().toString(36);const admin={'oai-authenticated-user-id':'v3-admin','oai-authenticated-user-email':'seedy@sites.test',origin:base};
async function req(route,body,headers=admin,status=200){const r=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{...headers,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,status,JSON.stringify({route,d}));return d}const op=(action,body={},status=200)=>req('/api/ops',{action,...body},admin,status),rpc=(action,body={},status=200)=>req('/api/worker',{action,...body},{Authorization:'Bearer '+token},status),snapshot=()=>req('/api/ops');const results=[];
await req('/api/ops',undefined,{},403);await req('/api/worker',{action:'claim'},{Authorization:'Bearer invalid'},401);results.push('admin and worker authentication');
let data=await snapshot();await op('settings',{revision:data.revision,config:{...data.config,paused:true}});await op('seedSources');await op('sourceDefaults',{id:'source-0'});let audited=(await snapshot()).sources.find(x=>x.id==='source-0');assert(audited.tested_at);assert.equal(audited.enabled,0);await op('source',{source:{...JSON.parse(audited.config),enabled:true}});await op('source',{source:{...JSON.parse(audited.config),enabled:false}});await op('sourceDefaults',{id:'dc-ib_new2'});audited=(await snapshot()).sources.find(x=>x.id==='dc-ib_new2');assert.equal(audited.tested_at,null);await op('source',{source:{...JSON.parse(audited.config),enabled:true}},409);results.push('live audit evidence application: PASS can enable, blocked cannot');const id='fixture-'+run,s=sourceSchema.parse({id,name:'검증 소스',url:'https://example.com/best',dailyLimit:1});await op('source',{source:{...s,enabled:true}},409);await op('source',{source:s});await op('scan',{id,test:true});let {task}=await rpc('claim',{workerId:'qa-worker'});assert.equal(task.kind,'scan');const item={externalId:'first',url:'https://example.com/post/first',title:'새로운 웃음 '+run,publishedAt:Date.now(),metrics:{views:100,likes:10,comments:7},blocks:[{type:'text',text:'일반적인 유머 이야기 본문입니다. 오늘도 함께 웃어요. '+run}],comments:[{id:'c',text:'재밌네요'}],mediaHash:''};await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[item],validation:{version:2,identity:sourceIdentity(s),passed:true,listPage:1,fullPage:true,listCount:1,details:1,comments:1,media:1}}});await op('source',{source:{...s,enabled:true}});data=await snapshot();assert(data.sources.find(x=>x.id===id).tested_at);results.push('test scan while paused, validation gate');
await op('settings',{revision:data.revision,config:{...data.config,paused:false,gmailEnabled:true,gmailMailbox:'dedicated@example.com',gmailSenders:['news@example.com']}});await op('schedule');data=await snapshot();let job=data.jobs.find(x=>x.source_id===id);assert(job);await op('schedule');assert.equal((await snapshot()).jobs.filter(x=>x.source_id===id).length,1);await op('publishNow',{id:job.id});for(let i=0;i<5;i++){({task}=await rpc('claim',{workerId:'qa-worker'}));if(task?.kind==='publish')break;if(task)await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[]}})}assert.equal(task.kind,'publish');await rpc('complete',{id:task.id,token:task.lease_token,result:{blocks:item.blocks,warnings:[]}});const post=await req('/api/posts/'+job.id);assert.equal(post.post.title,item.title);assert.equal(post.comments.length,1);assert.equal(post.post.source_candidate,undefined);results.push('daily cap, scheduled publication, imported comments, private provenance');
await op('scan',{id,test:true});({task}=await rpc('claim',{workerId:'qa-worker'}));while(task.kind!=='scan'){await rpc('complete',{id:task.id,token:task.lease_token,result:{}});({task}=await rpc('claim',{workerId:'qa-worker'}))}await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[item,{...item,externalId:'dup',url:'https://example.com/post/dup'}],validation:{version:2,identity:sourceIdentity(s),passed:true,listPage:1,fullPage:true,listCount:2,details:2,comments:1,media:1}}});data=await snapshot();assert(data.candidates.some(x=>x.external_id==='dup'&&x.status==='duplicate'));results.push('repeated scan and cross-candidate hash dedup');
await op('gmail');({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.kind,'gmail');const auth={id:task.id,token:task.lease_token};const mail={providerId:'m'+run,messageId:'message'+run,sender:'news@example.com',subject:'경제 동향 '+run,body:'오늘 경제 지표와 시장 분위기를 요약합니다. '+run,receivedAt:Date.now(),labels:['AUTO_POST'],mailbox:'dedicated@example.com'};const safe=await rpc('mail',{...auth,message:mail});assert.equal(safe.status,'published');const dup=await rpc('mail',{...auth,message:mail});assert(dup.duplicate);const pii=await rpc('mail',{...auth,message:{...mail,providerId:'p'+run,messageId:'pii'+run,body:'연락처 private@example.com '+run}});assert.equal(pii.status,'review_required');await rpc('mail',{...auth,message:{...mail,mailbox:'personal@example.com'}},403);await op('mailApprove',{id:pii.id,title:'경제 요약',body:'개인정보를 제거한 경제 요약입니다. '+run});await rpc('complete',{...auth,result:{}});const economy=await req('/api/posts?board='+encodeURIComponent('경제'));assert(economy.posts.some(x=>x.id===safe.id));results.push('Gmail dedicated mailbox, privacy hold, edit approval, dedup, economy feed');
({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.kind,'gmailLabel');assert.equal(task.payload.outcome,'DONE');assert.equal(task.payload.providerId,'p'+run);await rpc('complete',{id:task.id,token:task.lease_token,result:{label:'AUTO_POST_DONE'}});
const short=await op('shortCreate',{postIds:[job.id],config:{autoCombine:false}});await op('shortCreate',{postIds:[job.id],config:{autoCombine:false}},409);({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.kind,'render');await rpc('heartbeat',{id:task.id,token:task.lease_token});await op('shortApprove',{id:short.id},409);await op('shortCancel',{id:short.id});await rpc('heartbeat',{id:task.id,token:task.lease_token},409);results.push('shorts duplicate lock, heartbeat, QC approval gate, cancellation');
await op('source',{source:{...s,mediaHosts:['changed.example.com'],enabled:true}},409);await op('scan',{id,test:true});({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.kind,'scan');await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[item],validation:{passed:false}}});data=await snapshot();assert.equal(data.sources.find(x=>x.id===id).tested_at,null);assert.equal(data.sources.find(x=>x.id===id).enabled,0);await op('source',{source:{...s,enabled:true}},409);results.push('parser changes and failed revalidation revoke ON eligibility');
// Manually created sources use the same validation gate and expose live test state.
const manual=sourceSchema.parse({name:'수동 추가 '+run,url:'https://example.com/manual'});const created=await op('source',{source:manual,testAfterSave:true});assert(created.id);data=await snapshot();let custom=data.sources.find(x=>x.id===created.id);assert.equal(custom.enabled,0);assert.equal(custom.can_enable,false);assert.equal(custom.validation_status,'검사 대기');await op('scan',{id:created.id,test:true});({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.ref_id,created.id);assert.equal((await snapshot()).sources.find(x=>x.id===created.id).validation_status,'검사 중');await op('source',{source:{...manual,id:created.id,enabled:true}},409);await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[{...item,externalId:'manual',url:'https://example.com/manual/1'}],validation:{version:2,identity:sourceIdentity(manual),passed:true,listPage:1,fullPage:true,listCount:20,details:1,comments:2,media:1}}});custom=(await snapshot()).sources.find(x=>x.id===created.id);assert.equal(custom.validation_status,'통과');assert.equal(custom.can_enable,true);await op('source',{source:{...manual,id:created.id,enabled:true}});await op('source',{source:{...manual,id:created.id,enabled:false}});await op('scan',{id:'missing-source',test:true},404);results.push('manual add and test: OFF, queued, running, PASS, ON gate, invalid ID');
// Deletion is protected during active work, cancels queued work, and preserves published content.
await op('scan',{id:created.id,test:true});({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.ref_id,created.id);
await op('sourceDelete',{id:created.id},409);
await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[],validation:{passed:false}}});
await op('scan',{id:created.id,test:true});await op('sourceDelete',{id:created.id});
assert(!(await snapshot()).sources.some(x=>x.id===created.id));await op('scan',{id:created.id,test:true},404);
assert.equal((await rpc('claim',{workerId:'qa-worker'})).task,null);
await op('sourceDelete',{id});assert.equal((await req('/api/posts/'+job.id)).post.title,item.title);
await op('sourceDelete',{id:'missing-source'},404);
results.push('source deletion: active work protected, queued scan cancelled, published post preserved');
// Bulk actions preserve unselected sites and fields and prevent duplicate scans.
const ba=await op('source',{source:{...manual,name:'bulk A',url:'https://example.com/bulk-a'}}),bb=await op('source',{source:{...manual,name:'bulk B',url:'https://example.com/bulk-b'}});
await op('sourcesBulk',{ids:[ba.id],mode:'settings',patch:{commentLimit:0,images:false,videos:false}});
data=await snapshot();let ac=JSON.parse(data.sources.find(x=>x.id===ba.id).config);assert.equal(ac.commentLimit,0);assert.equal(ac.url,'https://example.com/bulk-a');assert.equal(JSON.parse(data.sources.find(x=>x.id===bb.id).config).commentLimit,5);
await op('sourcesBulk',{ids:[ba.id],mode:'settings',patch:{url:'https://other.example.com'}},400);
await op('sourcesBulk',{ids:[ba.id],mode:'settings',patch:{}},400);
await op('sourcesBulk',{ids:[ba.id],mode:'settings',patch:{commentLimit:-1}},400);
let bulk=await op('sourcesBulk',{ids:[ba.id,ba.id,bb.id],mode:'test'});assert.equal(bulk.results.length,2);assert(bulk.results.every(r=>r.status==='queued'));
bulk=await op('sourcesBulk',{ids:[ba.id,bb.id],mode:'test'});assert(bulk.results.every(r=>r.status==='skipped'));
({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.ref_id,ba.id);
bulk=await op('sourcesBulk',{ids:[ba.id],mode:'settings',patch:{dailyLimit:2}});assert.equal(bulk.results[0].status,'skipped');
await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[item],validation:{version:2,identity:sourceIdentity(ac),passed:true,listPage:1,fullPage:true,listCount:1,details:1,comments:0,media:0}}});
assert((await snapshot()).sources.find(x=>x.id===ba.id).can_enable);
await op('source',{source:{...ac,enabled:true}});await op('sourcesBulk',{ids:[ba.id],mode:'settings',patch:{dailyLimit:2}});
let ar=(await snapshot()).sources.find(x=>x.id===ba.id);assert.equal(ar.enabled,1);assert(ar.can_enable);
await op('sourcesBulk',{ids:[ba.id],mode:'settings',patch:{commentLimit:1}});ar=(await snapshot()).sources.find(x=>x.id===ba.id);assert.equal(ar.enabled,0);assert.equal(ar.can_enable,false);
await op('sourceDelete',{id:ba.id});await op('sourceDelete',{id:bb.id});
results.push('bulk selection and partial patches, validation invalidation, preserved verification, duplicate suppression, active work protection');
const humor=await op('source',{source:{name:'수동 웃대',url:'https://web.humoruniv.com/board/humor/board_best.html'}});await op('sourceDefaults',{id:humor.id});const humorRow=(await snapshot()).sources.find(r=>r.id===humor.id);const humorConfig=JSON.parse(humorRow.config);assert.equal(humorConfig.id,humor.id);assert.equal(humorConfig.name,'수동 웃대');assert.equal(humorConfig.selectors.body,'#wrap_copy');assert.equal(humorConfig.enabled,false);assert(humorConfig.mediaHosts.includes('down.humoruniv.com'));await op('sourceDelete',{id:humor.id});results.push('manual Humoruniv source can apply matching host preset without changing identity');
const nr=await op('source',{source:{name:'메모 테스트',url:'https://example.com/note'}});const nb=(await snapshot()).sources.find(r=>r.id===nr.id);await op('sourceNote',{id:nr.id,note:'댓글 0 재검사 필요'});let na=(await snapshot()).sources.find(r=>r.id===nr.id);assert.equal(na.source_note,'댓글 0 재검사 필요');assert.equal(na.config,nb.config);assert.equal(na.tested_at,nb.tested_at);await op('sourceNote',{id:nr.id,note:''});na=(await snapshot()).sources.find(r=>r.id===nr.id);assert.equal(na.source_note,'');await op('sourceNote',{id:nr.id,note:'x'.repeat(1501)},400);await op('sourceNote',{id:'missing-note',note:'test'},404);await op('sourceDelete',{id:nr.id});results.push('source notes persist, clear, validate length and leave collection settings unchanged');
// V3 list-only evidence must enable without detail, comments, or media requests.
const listConfig=sourceSchema.parse({name:'목록 전용 QA',url:'https://example.com/list',collectionMode:'LIST_ONLY',requiredFields:['title','sourceUrl','sourcePostId']});
const listCreated=await op('source',{source:listConfig});await op('scan',{id:listCreated.id,test:true});({task}=await rpc('claim',{workerId:'qa-worker'}));assert.equal(task.ref_id,listCreated.id);
const listItem={...item,externalId:'list-'+run,title:'목록 글 '+run,url:'https://example.com/list/'+run,collectionMode:'LIST_ONLY',policyIdentity:sourceIdentity(listConfig),availableFields:['title','sourceUrl','sourcePostId'],blocks:[{type:'link',url:'https://example.com/list/'+run}],comments:[]};
await rpc('complete',{id:task.id,token:task.lease_token,result:{items:[listItem],validation:{version:3,identity:sourceIdentity(listConfig),mode:'LIST_ONLY',passed:true,listPage:1,fullPage:true,listCount:30,details:0,comments:0,media:0,eligibleCount:1,samples:[{eligible:true,availableFields:listItem.availableFields}]}}});
let listRow=(await snapshot()).sources.find(r=>r.id===listCreated.id);assert(listRow.can_enable);assert.equal(JSON.parse(listRow.config).resolvedMode,'LIST_ONLY');await op('source',{source:{...JSON.parse(listRow.config),enabled:true}});
await op('sourcesBulk',{ids:[listCreated.id],mode:'settings',patch:{requiredFields:['title','sourceUrl','sourcePostId','body','image']}});listRow=(await snapshot()).sources.find(r=>r.id===listCreated.id);assert.equal(listRow.can_enable,false);assert.equal(listRow.enabled,0);await op('sourceDelete',{id:listCreated.id});results.push('V3 list-only passes with zero detail/comments/media; detected mode persists; stronger required fields revoke eligibility');
// Leave this isolated QA environment paused after assertions.
data=await snapshot();await op('settings',{revision:data.revision,config:{...data.config,paused:true}});writeFileSync('test-results/automation-api.json',JSON.stringify({passed:true,at:new Date().toISOString(),results},null,2));console.log('PASS:',results.join('; '));
