import test from 'node:test';import assert from 'node:assert/strict';import {sourceSchema} from '../lib/automation/config.ts';import {validateSource} from '../worker/validate-source.mjs';import {scanSource} from '../worker/adapters.mjs';import {validEvidence} from '../lib/automation/validation.mjs';
const base=['title','sourceUrl','sourcePostId'],url='https://example.com/list',jpg=Buffer.from([255,216,255,224,0,0,0,0]);
function fixture({list='<article><h2>A</h2><a href="/post/1">A</a></article>',body='<article>Body<img src="/image.jpg"></article>',mediaFail=false,commentDeny=false}={}){const calls=[];return {calls,fetcher:async(u,o)=>{calls.push({url:u,method:o?.method||'GET'});if(u===url)return {bytes:Buffer.from(list),type:'text/html'};if(u.endsWith('/image.jpg'))return {bytes:jpg,type:'application/octet-stream'};if(u.endsWith('/bad.mp4')||mediaFail)throw Error('HTTP 404');if(u.includes('/board/comment/'))return {bytes:Buffer.from(commentDeny?'denied':'{"comments":[]}'),type:'text/html'};return {bytes:Buffer.from(body),type:'text/html'}}}}
const cfg=o=>sourceSchema.parse({name:'fixture',url,...o});
test('empty successful list response is not mislabeled as a selector mismatch',async()=>{const r=await validateSource(cfg({}),{fetcher:async()=>({bytes:Buffer.from('  '),type:'text/html'})});assert(!r.validation.passed);assert.deepEqual(r.errors,['EMPTY_RESPONSE: list']);});
test('one denied media file does not disable other files on the same server; denied URL is not retried',async()=>{const calls=[];const r=await validateSource(cfg({}),{fetcher:async u=>{calls.push(u);if(u===url)return {bytes:Buffer.from('<article><h2>A</h2><a href="/post/1">A</a></article>'),type:'text/html'};if(u.endsWith('/bad.jpg'))throw Error('BLOCKED: HTTP 403');if(u.endsWith('/good.jpg'))return {bytes:jpg,type:'image/jpeg'};return {bytes:Buffer.from('<article>Body<img src="/bad.jpg"><img src="/bad.jpg"><img src="/good.jpg"></article>'),type:'text/html'}}});assert(r.validation.passed);assert.equal(calls.filter(u=>u.endsWith('/bad.jpg')).length,1);assert(calls.some(u=>u.endsWith('/good.jpg')));});
test('rate limits stop further media requests to the same server',async()=>{const calls=[];const r=await validateSource(cfg({}),{fetcher:async u=>{calls.push(u);if(u===url)return {bytes:Buffer.from('<article><h2>A</h2><a href="/post/1">A</a></article>'),type:'text/html'};if(u.endsWith('.jpg'))throw Error('BLOCKED: HTTP 429');return {bytes:Buffer.from('<article>Body<img src="/a.jpg"><img src="/b.jpg"></article>'),type:'text/html'}}});assert(!r.validation.passed);assert.equal(calls.filter(u=>u.endsWith('.jpg')).length,1);});
test('AUTO metadata sufficiency uses LIST_ONLY and never follows detail or media URLs',async()=>{const f=fixture({list:'<article><h2>A</h2><a href="/403">A</a><img src="https://unallowed.example.com/a.jpg"></article>'}),s=cfg({requiredFields:base});const r=await validateSource(s,f);assert(r.validation.passed);assert.equal(r.validation.mode,'LIST_ONLY');assert.equal(f.calls.length,1);assert.equal(r.validation.details,0);assert(validEvidence(s,r.validation));assert(r.items[0].blocks.some(b=>b.type==='link'));assert(!r.items[0].blocks.some(b=>b.type==='image'));});
test('AUTO body and image available in list chooses LIST_WITH_MEDIA without detail',async()=>{const f=fixture({list:'<article><h2>A</h2><a href="/post/1">A</a><div class="summary">Preview body</div><img src="/image.jpg" width="120"></article>'}),s=cfg({});const r=await validateSource(s,f);assert(r.validation.passed);assert.equal(r.validation.mode,'LIST_WITH_MEDIA');assert.equal(f.calls.length,2);assert(!f.calls.some(c=>c.url.endsWith('/post/1')));assert(r.validation.availableFields.includes('image'));});
test('AUTO requires body and image and ignores optional comments',async()=>{const f=fixture(),s=cfg({});const r=await validateSource(s,f);assert(r.validation.passed);assert.equal(r.validation.mode,'DETAIL_NO_COMMENTS');assert.equal(r.validation.stages.comments.status,'unused');assert.equal(f.calls.length,3);assert(!validEvidence({...s,requiredFields:[...base,'comments']},r.validation));});
test('AUTO does not request optional video merely because its URL exists',async()=>{const f=fixture({body:'<article>Body<img src="/image.jpg"><video src="/bad.mp4"></video></article>'}),r=await validateSource(cfg({}),f);assert(r.validation.passed);assert(!f.calls.some(c=>c.url.endsWith('/bad.mp4')));assert.equal(r.validation.media,1);});
test('AUTO reevaluates list structure instead of forcing a previously detected detail mode',async()=>{const f=fixture({list:'<article><h2>A</h2><a href="/post/1">A</a><p class="summary">Body</p><img src="/image.jpg"></article>'}),r=await scanSource(cfg({resolvedMode:'DETAIL_NO_COMMENTS'}),f);assert.equal(r.validation.mode,'LIST_WITH_MEDIA');assert(!f.calls.some(c=>c.url.endsWith('/post/1')));});
test('TEXT_ONLY makes no image request even with media switches on',async()=>{const f=fixture(),r=await validateSource(cfg({collectionMode:'DETAIL_TEXT_ONLY'}),f);assert(r.validation.passed);assert.equal(f.calls.length,2);assert(!r.items[0].blocks.some(b=>b.type==='image'));});
test('required body does not downgrade to a link when detail is forbidden',async()=>{const calls=[],r=await validateSource(cfg({}),{fetcher:async u=>{calls.push(u);if(u===url)return {bytes:Buffer.from('<article><h2>A</h2><a href="/forbidden">A</a></article>'),type:'text/html'};throw Error('BLOCKED: HTTP 403')}});assert(!r.validation.passed);assert(r.validation.errors.some(e=>e.includes('403')));assert(r.validation.alternatives.some(a=>a.mode==='LINK_AGGREGATION'));assert.equal(calls.length,2);});
test('FULL optional DC comment denial is a warning; required comments fail',async()=>{const dc='https://gall.dcinside.com/board/lists/?id=test';for(const required of [false,true]){const calls=[],s=cfg({url:dc,adapter:'dcinside',collectionMode:'FULL',images:false,videos:false,requiredFields:[...base,'body',...(required?['comments']:[])]});const r=await validateSource(s,{fetcher:async(u,o)=>{calls.push(u);return {bytes:Buffer.from(o?.method==='POST'?'denied':u===dc?'<article><h2>A</h2><a href="/board/view/?id=test&no=1">A</a></article>':'<article>Body</article><input id="e_s_n_o" value="token">'),type:'text/html'}}});assert.equal(r.validation.passed,!required);assert.equal(calls.length,3);assert((required?r.errors:r.validation.warnings).some(e=>e.includes('DC public comment')))}});
test('optional video failure does not revoke required body and image',async()=>{const f=fixture({body:'<article>Body<img src="/image.jpg"><video src="/bad.mp4"></video></article>'}),r=await validateSource(cfg({collectionMode:'DETAIL_NO_COMMENTS'}),f);assert(r.validation.passed);assert(r.validation.warnings.some(e=>e.includes('404')));assert(!r.items[0].blocks.some(b=>b.type==='video'));});
test('LINK_AGGREGATION only copies short list summary and URL',async()=>{const f=fixture({list:'<article><h2>A</h2><a href="/post/1">A</a><p class="summary">'+ 'x'.repeat(900)+'</p></article>'}),s=cfg({collectionMode:'LINK_AGGREGATION'}),r=await scanSource(s,f);assert.equal(f.calls.length,1);assert.equal(r.items[0].blocks[0].text.length,500);assert(r.items[0].blocks.some(b=>b.type==='link'));assert(validEvidence(s,r.validation));});
test('required fields must coexist in one post; disabled required stages do not pass',async()=>{const f=fixture({list:'<article><h2>A</h2><a href="/a">A</a><p class="summary">body</p></article><article><h2>B</h2><a href="/b">B</a><img src="/image.jpg"></article>'}),r=await validateSource(cfg({collectionMode:'LIST_WITH_MEDIA',requiredFields:[...base,'body','image']}),f);assert(!r.validation.passed);assert(!validEvidence(cfg({collectionMode:'LIST_WITH_MEDIA',requiredFields:[...base,'body','image']}),r.validation));const q=await validateSource(cfg({collectionMode:'LIST_ONLY',requiredFields:[...base,'image']}),fixture());assert(!q.validation.passed);assert(q.errors.some(e=>e.includes('DISABLED')));});
