import test from 'node:test';import assert from 'node:assert/strict';import {robotsPolicy} from '../worker/network.mjs';import {sourceIdentity,validEvidence} from '../lib/automation/validation.mjs';import {sourceSchema} from '../lib/automation/config.ts';import {pollGmail,relabelGmail} from '../worker/google.mjs';
test('robots wildcard, end anchor, longest allow and query rules',()=>{const r='User-agent: *\nDisallow: /*/edit$\nDisallow: /private\nAllow: /private/public\nDisallow: /*?*list_context=\nCrawl-delay: 2';for(const path of ['/best','/post/1','/edit/article','/private/public'])assert(robotsPolicy(r,'https://example.com'+path).allowed);for(const path of ['/post/edit','/private/x','/post/1?list_context=x'])assert(!robotsPolicy(r,'https://example.com'+path).allowed);assert.equal(robotsPolicy(r,'https://example.com').delay,2);assert(robotsPolicy('User-agent: *\nDisallow: /\nUser-agent: SecretAgitBot\nAllow: /best','https://example.com/best').allowed)});
test('source gate rejects old, partial and changed evidence',()=>{const s=sourceSchema.parse({name:'test',url:'https://example.com/best'}),e={version:2,identity:sourceIdentity(s),listPage:1,fullPage:true,listCount:30,details:1,comments:2,media:1,passed:true};assert(validEvidence(s,e));for(const change of [{version:1},{fullPage:false},{comments:0},{media:0},{passed:false}])assert(!validEvidence(s,{...e,...change}));assert(!validEvidence({...s,mediaHosts:['example.org']},e));assert(!validEvidence({...s,adapter:'dcinside'},e))});
const cfg={gmailEnabled:true,gmailMailbox:'dedicated@example.com',gmailSenders:['news@example.com'],gmailLabel:'AUTO_POST'};
function fixture({failLabel=false}={}){const calls=[],moves=[];const fetcher=async(url,o={})=>{calls.push(url);if(url.includes('oauth2'))return Response.json({access_token:'test'});if(url.endsWith('/profile'))return Response.json({emailAddress:cfg.gmailMailbox});if(url.endsWith('/labels')){if(o.method==='POST')return Response.json({id:JSON.parse(o.body).name});return Response.json({labels:[{name:'AUTO_POST',id:'source'}]})}if(url.includes('/modify')){if(failLabel)return Response.json({}, {status:503});moves.push({id:url.split('/').at(-2),...JSON.parse(o.body)});return Response.json({})}if(url.includes('format=full')){const id=url.split('/').at(-1).split('?')[0];return Response.json({id,labelIds:['source'],payload:{mimeType:'text/plain',body:{data:Buffer.from('경제 요약').toString('base64url')},headers:[{name:'From',value:'news@example.com'},{name:'Subject',value:'경제'}]}})}return Response.json(url.includes('pageToken')?{messages:[{id:'review'},{id:'error'}]}:{messages:[{id:'done'}],nextPageToken:'next'})};return {fetcher,calls,moves}}
function env(){for(const key of ['CLIENT_ID','CLIENT_SECRET','REFRESH_TOKEN'])process.env['GMAIL_'+key]='fixture'}
test('Gmail snapshots pages, creates labels, routes done review failure, and removes source',async()=>{env();const f=fixture();const result=await pollGmail(cfg,m=>{if(m.providerId==='error')throw Error('processing failed');return {status:m.providerId==='done'?'published':'review_required'}},f.fetcher);assert.deepEqual([result.done,result.review,result.error],[1,1,1]);assert.equal(result.pages,2);assert(f.calls.findIndex(u=>u.includes('pageToken'))<f.calls.findIndex(u=>u.includes('format=full')));for(const m of f.moves){assert.deepEqual(m.addLabelIds,['AUTO_POST_'+m.id.toUpperCase()]);assert(m.removeLabelIds.includes('source'));assert(!m.removeLabelIds.includes(m.addLabelIds[0]))}});
test('Gmail failed label mutation surfaces retry; manual approval relabels review to done',async()=>{env();await assert.rejects(()=>pollGmail(cfg,()=>({status:'published'}),fixture({failLabel:true}).fetcher),/GMAIL_LABEL_UPDATE_FAILED/);const f=fixture();await relabelGmail(cfg,'review','DONE',f.fetcher);assert(f.moves[0].removeLabelIds.includes('AUTO_POST_REVIEW'));assert.deepEqual(f.moves[0].addLabelIds,['AUTO_POST_DONE']);await assert.rejects(()=>relabelGmail({...cfg,gmailLabel:'AUTO_POST_DONE'},'x','DONE',f.fetcher),/INVALID_SOURCE_LABEL/)});

test('DC normal login footer is not a block; public comment rejection stops without fallback',async()=>{const {DcinsideAdapter}=await import('../worker/adapters.mjs');const source=sourceSchema.parse({name:'dc',adapter:'dcinside',url:'https://gall.dcinside.com/board/lists/?id=test'});const calls=[];const adapter=new DcinsideAdapter(async(url,o)=>{calls.push({url,method:o?.method});return {bytes:Buffer.from(o?.method==='POST'?'정상적인 접근이 아닙니다.':url===source.url?'<article><h2>글</h2><a href="/board/view/?id=test&no=1">글</a></article><footer>로그인이 필요합니다.</footer>':'<article>본문</article><input id="e_s_n_o" value="public-fixture">'),type:'text/html; charset=utf-8'}});const list=await adapter.scanList(source);assert.equal(list.length,1);await assert.rejects(()=>adapter.loadDetail(list[0],source),/BLOCKED/);assert.equal(calls.length,3);assert.equal(calls[2].method,'POST')});
test('public AJAX comments preserve IDs and strip executable markup',async()=>{const {publicComments}=await import('../worker/public-comments.mjs');const source={commentLimit:5};const a=await publicComments({url:'https://theqoo.net/hot/123',comments:[]},'loadReply(123,0)',source,async()=>({bytes:Buffer.from(JSON.stringify({comment_list:[{srl:1,ct:'<p>댓글<script>bad()</script></p>'}]}))}));assert.deepEqual(a.comments,[{id:'1',text:'댓글'}]);const b=await publicComments({url:'https://www.inven.co.kr/board/webzine/2097/123',comments:[]},"PwCMT.constructor({comeidx:'2097',articlecode:123})",source,async()=>({bytes:Buffer.from(JSON.stringify({commentlist:[{list:[{__attr__:{cmtidx:77},o_comment:'인벤 댓글'}]}]}))}));assert.deepEqual(b.comments,[{id:'77',text:'인벤 댓글'}])});
