import {z} from 'zod';import {wrap,db,bounded,HttpError} from '@/lib/server';import {workerAuth,claim,lease,failTask,event,type Row} from '@/lib/automation/server';import {acceptScan,publishCandidate,tick} from '@/lib/automation/collect';import {taskStatement} from '@/lib/automation/server';import {ingestMail} from '@/lib/automation/mail';
export const POST=wrap(async req=>{await workerAuth(req);const d=z.record(z.string(),z.unknown()).parse(JSON.parse(new TextDecoder().decode(await bounded(req.body,2500000))));const action=z.string().parse(d.action);
if(action==='claim'){await tick();return Response.json({task:await claim(z.string().max(100).parse(d.workerId),d.capabilities||{})})}
const id=z.string().uuid().parse(d.id),token=z.string().uuid().parse(d.token),task=await lease(id,token);
if(action==='heartbeat'){await db().prepare("UPDATE worker_tasks SET lease_until=?,updated_at=? WHERE id=? AND lease_token=? AND status='running'").bind(Date.now()+180000,Date.now(),id,token).run();return Response.json({ok:true})}
if(action==='fail'){await failTask(task,z.string().max(1000).parse(d.error),d.blocked===true);return Response.json({ok:true})}
if(action==='stage'){const stage=z.enum(['analyzing','ready_to_render','rendering','qc']).parse(d.stage);if(task.kind!=='render')throw new HttpError(400,'잘못된 단계');await db().prepare('UPDATE shorts_jobs SET status=?,progress=?,plan=? WHERE id=?').bind(stage,z.number().min(0).max(100).parse(d.progress),JSON.stringify(d.plan||{}),task.ref_id).run();await event(String(task.ref_id),stage);return Response.json({ok:true})}
if(action==='split'){if(task.kind!=='render')throw new HttpError(400,'잘못된 작업');const count=z.number().int().min(2).max(100).parse(d.partCount);const parent=await db().prepare('SELECT * FROM shorts_jobs WHERE id=?').bind(task.ref_id).first<Row>();if(!parent)throw new HttpError(404,'작업 없음');const settings=JSON.parse(String(parent.config));const posts=(await db().prepare('SELECT post_id,sequence FROM shorts_job_posts WHERE job_id=?').bind(task.ref_id).all()).results;const statements=[];for(let part=1;part<count;part++){const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(task.ref_id)+':'+part))),n=>n.toString(16).padStart(2,'0')).join('');const child=digest.slice(0,8)+'-'+digest.slice(8,12)+'-4'+digest.slice(13,16)+'-a'+digest.slice(17,20)+'-'+digest.slice(20,32);statements.push(db().prepare("INSERT OR IGNORE INTO shorts_jobs(id,status,created_by,config,plan,progress,error,retry_count,approved_at,created_at,completed_at) VALUES(?,'queued',?,?,'{}',0,'',0,NULL,?,NULL)").bind(child,parent.created_by,JSON.stringify({...settings,partIndex:part}),Date.now()));for(const p of posts)statements.push(db().prepare('INSERT OR IGNORE INTO shorts_job_posts(id,job_id,post_id,sequence) VALUES(?,?,?,?)').bind(child+'-'+p.sequence,child,p.post_id,p.sequence));const old=await db().prepare("SELECT id FROM worker_tasks WHERE ref_id=? AND kind='render'").bind(child).first();if(!old)statements.push(taskStatement('render',child,{},Date.now(),settings.maxRetries+1));}await db().batch(statements);return Response.json({ok:true,partCount:count})}
if(action==='uploadSession'){if(task.kind!=='upload')throw new HttpError(400,'잘못된 작업');const url=z.string().url().parse(d.url);if(new URL(url).hostname!=='www.googleapis.com')throw new HttpError(400,'업로드 주소 검증 실패');await db().prepare('UPDATE shorts_publications SET upload_session=? WHERE id=?').bind(url,task.ref_id).run();return Response.json({ok:true})}
if(action==='mail'){if(task.kind!=='gmail')throw new HttpError(400,'잘못된 작업');return Response.json(await ingestMail(d.message))}
if(action!=='complete')throw new HttpError(400,'지원하지 않는 작업');const result=z.record(z.string(),z.unknown()).parse(d.result||{});let response:unknown={ok:true};
switch(task.kind){case 'scan':response=await acceptScan(String(task.ref_id),result.items,JSON.parse(String(task.payload)).test===true,result.validation);break;
case 'publish':response=await publishCandidate(String(task.ref_id),result);break;
case 'render':{const out=z.object({key:z.string().regex(/^shorts\/[a-f0-9-]+\.mp4$/),width:z.literal(1080),height:z.literal(1920),fps:z.literal(30),durationMs:z.number().positive(),size:z.number().positive(),audioMode:z.string(),qc:z.object({passed:z.literal(true)}).passthrough(),plan:z.record(z.string(),z.unknown())}).parse(result);const record=await db().prepare('SELECT id FROM shorts_assets WHERE storage_key=? AND type=?').bind(out.key,'output').first();if(!record)throw new HttpError(400,'저장된 출력 파일이 없습니다.');await db().batch([db().prepare("INSERT INTO shorts_outputs(id,job_id,storage_key,width,height,fps,duration_ms,file_size,audio_mode,qc_status,qc_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,'passed',?,?) ON CONFLICT(job_id) DO UPDATE SET storage_key=excluded.storage_key,width=excluded.width,height=excluded.height,fps=excluded.fps,duration_ms=excluded.duration_ms,file_size=excluded.file_size,audio_mode=excluded.audio_mode,qc_status='passed',qc_json=excluded.qc_json").bind(crypto.randomUUID(),task.ref_id,out.key,1080,1920,30,Math.round(out.durationMs),out.size,out.audioMode,JSON.stringify(out.qc),Date.now()),db().prepare("UPDATE shorts_jobs SET status='ready',plan=?,progress=100,error='',completed_at=? WHERE id=?").bind(JSON.stringify(out.plan),Date.now(),task.ref_id)]);break}
case 'upload':{const r=z.object({videoId:z.string().regex(/^[\w-]{11}$/),channelId:z.string(),status:z.enum(['private','unlisted','scheduled','published'])}).parse(result);await db().prepare('UPDATE shorts_publications SET external_id=?,status=?,last_synced_at=?,published_at=CASE WHEN ? THEN ? ELSE NULL END,error=? WHERE id=?').bind(r.videoId,r.status,Date.now(),r.status==='published'?1:0,Date.now(),'',task.ref_id).run();const p=await db().prepare('SELECT job_id,metadata FROM shorts_publications WHERE id=?').bind(task.ref_id).first<Row>();if(p)await db().prepare('UPDATE shorts_publications SET metadata=? WHERE id=?').bind(JSON.stringify({...JSON.parse(String(p.metadata)),channelId:r.channelId}),task.ref_id).run();break}
case 'sync':{const r=z.object({views:z.number(),likes:z.number(),comments:z.number(),status:z.enum(['private','unlisted','scheduled','published'])}).parse(result);await db().batch([db().prepare('INSERT INTO shorts_metrics(id,publication_id,measured_at,views,likes,comments,raw) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),task.ref_id,Date.now(),r.views,r.likes,r.comments,JSON.stringify(result)),db().prepare('UPDATE shorts_publications SET last_synced_at=?,status=? WHERE id=?').bind(Date.now(),r.status,task.ref_id)]);break}
}
await db().prepare("UPDATE worker_tasks SET status='completed',lease_token=NULL,lease_until=NULL,updated_at=? WHERE id=? AND lease_token=?").bind(Date.now(),id,token).run();await event(String(task.ref_id),'completed');return Response.json(response)});
