export type Block =
 | {type:'text';text:string}
 | {type:'image';id:string}
 | {type:'video';id:string}
 | {type:'youtube';videoId:string}
 | {type:'link';url:string};
export type PopularKind='site'|'today'|'srrr';
export type Settings={autoplay:boolean;copyProtection:boolean;popularComments:number;popularLikes:number;popularViews:number;popularMode:'all'|'any';popularDays:number;popularLimit:number;todayPopularComments:number;todayPopularLikes:number;todayPopularViews:number;todayPopularMode:'all'|'any';todayPopularDays:number;todayPopularLimit:number;srrrPopularComments:number;srrrPopularLikes:number;srrrPopularViews:number;srrrPopularMode:'all'|'any';srrrPopularDays:number;srrrPopularLimit:number;srrrPromotionLikes:number;imageCost:number;videoCost:number;textCost:number;signupPoints:number};
export const defaultSettings:Settings={autoplay:false,copyProtection:true,popularComments:5,popularLikes:10,popularViews:100,popularMode:'all',popularDays:7,popularLimit:20,todayPopularComments:5,todayPopularLikes:10,todayPopularViews:100,todayPopularMode:'all',todayPopularDays:7,todayPopularLimit:20,srrrPopularComments:5,srrrPopularLikes:10,srrrPopularViews:100,srrrPopularMode:'all',srrrPopularDays:7,srrrPopularLimit:20,srrrPromotionLikes:10,imageCost:10,videoCost:30,textCost:5,signupPoints:0};
export function youtubeId(value:string):string|null {try{const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)return null;const h=u.hostname.toLowerCase().replace(/^www\./,'');let id='';if(h==='youtu.be')id=u.pathname.split('/')[1];else if(['youtube.com','m.youtube.com','youtube-nocookie.com'].includes(h)){id=u.pathname==='/watch'?u.searchParams.get('v')||'':/^\/(shorts|embed|live)\//.test(u.pathname)?u.pathname.split('/')[2]:''}return /^[\w-]{11}$/.test(id)?id:null}catch{return null}}
export function safeLink(value:string):string|null {try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password&&value.length<=2000?u.href:null}catch{return null}}
export function splitLinks(text:string):Block[]{const result:Block[]=[];let end=0;for(const m of text.matchAll(/https?:\/\/[^\s<>"']+/g)){const url=m[0].replace(/[.,!?;:)\]}]+$/,'');const safe=safeLink(url);if(!safe)continue;if(m.index!>end)result.push({type:'text',text:text.slice(end,m.index)});const videoId=youtubeId(safe);result.push(videoId?{type:'youtube',videoId}:{type:'link',url:safe});end=m.index!+url.length}if(end<text.length)result.push({type:'text',text:text.slice(end)});return result.length?result:[{type:'text',text}]}
export function popularRule(s:Settings,kind:PopularKind){const prefix=kind==='today'?'todayPopular':kind==='srrr'?'srrrPopular':'popular';return {comments:s[(prefix+'Comments') as keyof Settings] as number,likes:s[(prefix+'Likes') as keyof Settings] as number,views:s[(prefix+'Views') as keyof Settings] as number,mode:s[(prefix+'Mode') as keyof Settings] as 'all'|'any',days:s[(prefix+'Days') as keyof Settings] as number,limit:s[(prefix+'Limit') as keyof Settings] as number}}
export function popularPredicate(s:Settings,kind:PopularKind='site'){const r=popularRule(s,kind),checks:[string,number][]=[['comments',r.comments],['likes',r.likes],['views',r.views]];const active=checks.filter(([,v])=>v>0);return {sql:active.length?'('+active.map(([k])=>k+'>=?').join(r.mode==='all'?' AND ':' OR ')+')':'0',values:active.map(([,v])=>v),days:r.days,limit:r.limit}}


