import sourceAudit from '@/test-results/live-sources.json';
import {sourceIdentity,validEvidence} from '@/lib/automation/validation.mjs';
import {z} from 'zod';import {wrap,db,json,HttpError} from '@/lib/server';import {admin} from '@/lib/settings';import {opsSchema,sourceSchema} from '@/lib/automation/config';import {sourceCatalog} from '@/lib/automation/catalog';import {ops,enqueue,event,taskStatement} from '@/lib/automation/server';import {scheduleCandidates} from '@/lib/automation/collect';import {createShorts,queueUpload} from '@/lib/automation/shorts';import {publishMail} from '@/lib/automation/mail';
export const GET=wrap(async req=>{await admin();const u=new URL(req.url),offset=Math.max(0,Math.min(10000,Number(u.searchParams.get('offset'))||0));const q='%'+(u.searchParams.get('q')||'').slice(0,100)+'%',state=u.searchParams.get('state')||'';const [config,sources,candidates,jobs,runs,shorts,outputs,publications,metrics,mail,events,workers,assets,posts]=await Promise.all([ops(),db().prepare('SELECT * FROM auto_sources ORDER BY name').all(),db().prepare("SELECT * FROM auto_candidates WHERE title LIKE ? AND (?='' OR status=?) ORDER BY first_seen_at DESC LIMIT 50 OFFSET ?").bind(q,state,state,offset).all(),db().prepare('SELECT j.*,c.title FROM auto_post_jobs j JOIN auto_candidates c ON c.id=j.candidate_id ORDER BY scheduled_at DESC LIMIT 50 OFFSET ?').bind(offset).all(),db().prepare('SELECT * FROM crawl_runs ORDER BY started_at DESC LIMIT 30').all(),db().prepare('SELECT * FROM shorts_jobs ORDER BY created_at DESC LIMIT 50 OFFSET ?').bind(offset).all(),db().prepare('SELECT * FROM shorts_outputs ORDER BY created_at DESC LIMIT 50').all(),db().prepare('SELECT * FROM shorts_publications ORDER BY created_at DESC LIMIT 50').all(),db().prepare('SELECT * FROM shorts_metrics ORDER BY measured_at DESC LIMIT 50').all(),db().prepare('SELECT * FROM email_ingest_messages ORDER BY created_at DESC LIMIT 50 OFFSET ?').bind(offset).all(),db().prepare('SELECT * FROM job_events ORDER BY created_at DESC LIMIT 50').all(),db().prepare('SELECT * FROM worker_health').all(),db().prepare('SELECT * FROM shorts_assets ORDER BY created_at DESC').all(),db().prepare("SELECT p.id,p.title,p.category,p.created_at,p.thumbnail,p.body,p.views,p.short_excluded,(SELECT COUNT(*) FROM likes WHERE post_id=p.id) likes,(SELECT COUNT(*) FROM comments WHERE post_id=p.id) comments,(SELECT COUNT(*) FROM shorts_job_posts WHERE post_id=p.id) history FROM posts p WHERE p.hidden=0 AND p.title LIKE ? ORDER BY p.created_at DESC LIMIT 50 OFFSET ?").bind(q,offset).all()]);return Response.json({...config,sources:sources.results,candidates:candidates.results,jobs:jobs.results,runs:runs.results,shorts:shorts.results,outputs:outputs.results,publications:publications.results,metrics:metrics.results,mail:mail.results,events:events.results,workers:workers.results,assets:assets.results,posts:posts.results,offset},{headers:{'Cache-Control':'no-store'}})});
export const POST=wrap(async req=>{const user=await admin(req),d=z.record(z.string(),z.unknown()).parse(await json(req)),action=z.string().parse(d.action),id=typeof d.id==='string'?d.id:'';let result:unknown={ok:true};
switch(action){
case 'settings':{const cfg=opsSchema.parse(d.config),revision=z.number().int().parse(d.revision);const sql=revision===0?db().prepare("INSERT OR IGNORE INTO ops_settings(id,value,revision) VALUES('main',?,1)").bind(JSON.stringify(cfg)):db().prepare("UPDATE ops_settings SET value=?,revision=revision+1 WHERE id='main' AND revision=?").bind(JSON.stringify(cfg),revision);const r=await sql.run();if(!r.meta.changes)throw new HttpError(409,'설정이 변경됐습니다. 다시 불러오세요.');await db().batch([db().prepare("UPDATE system_profiles SET display_name=? WHERE id='system:auto'").bind(cfg.authorName),db().prepare("UPDATE system_profiles SET display_name=? WHERE id='system:economy'").bind(cfg.economyAuthor)]);break}
case 'seedSources':for(const s of sourceCatalog)await db().prepare("INSERT OR IGNORE INTO auto_sources(id,name,config,enabled,tested_at,last_run_at,last_success_at,last_error,created_at,updated_at) VALUES(?,?,?,0,NULL,NULL,NULL,'미검증 소스',?,?)").bind(s.id,s.name,JSON.stringify(s),Date.now(),Date.now()).run();break;
case 'source':{const s=sourceSchema.parse(d.source),sourceId=s.id||crypto.randomUUID(),old=await db().prepare('SELECT tested_at,config FROM auto_sources WHERE id=?').bind(sourceId).first<{tested_at:number|null;config:string}>();const previous=old?sourceSchema.parse(JSON.parse(old.config)):null;const changed=!previous||sourceIdentity(previous)!==sourceIdentity(s);const evidence=await db().prepare("SELECT counts FROM crawl_runs WHERE source_id=? AND status='completed' AND json_extract(counts,'$.validation') IS NOT NULL ORDER BY started_at DESC LIMIT 1").bind(sourceId).first<{counts:string}>();if(s.enabled&&(!old?.tested_at||changed||!validEvidence(s,evidence?JSON.parse(evidence.counts).validation:null)))throw new HttpError(409,'주소·선택자·댓글·미디어 수집 테스트를 먼저 통과해야 합니다.');await db().prepare("INSERT INTO auto_sources(id,name,config,enabled,tested_at,last_run_at,last_success_at,last_error,created_at,updated_at) VALUES(?,?,?,?,NULL,NULL,NULL,'미검증 소스',?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,config=excluded.config,enabled=excluded.enabled,tested_at=CASE WHEN ? THEN NULL ELSE auto_sources.tested_at END,updated_at=excluded.updated_at").bind(sourceId,s.name,JSON.stringify({...s,id:sourceId}),s.enabled?1:0,Date.now(),Date.now(),changed?1:0).run();break}
case 'sourceDefaults':{const s=sourceCatalog.find(x=>x.id===id);if(!s)throw new HttpError(404,'기본 소스 없음');const old=await db().prepare('SELECT config FROM auto_sources WHERE id=?').bind(id).first<{config:string}>();const merged={...(old?JSON.parse(old.config):s),url:s.url,adapter:s.adapter,selectors:s.selectors,mediaHosts:s.mediaHosts,enabled:false};await db().prepare("UPDATE auto_sources SET config=?,enabled=0,tested_at=NULL,last_error='수정된 기본값 적용: 재검증 필요',updated_at=? WHERE id=?").bind(JSON.stringify(merged),Date.now(),id).run();const audit=sourceAudit.find(r=>r.id===id&&r.status==='PASS');if(audit&&validEvidence(merged,audit.validation)){const at=Date.parse(audit.at);await db().batch([db().prepare("INSERT INTO crawl_runs(id,source_id,status,counts,error,started_at,finished_at) VALUES(?,?,'completed',?,'',?,?)").bind(crypto.randomUUID(),id,JSON.stringify({scanned:audit.listCount,validation:audit.validation,origin:'live-source-audit'}),at,at),db().prepare("UPDATE auto_sources SET tested_at=?,last_success_at=?,last_error='' WHERE id=?").bind(at,at,id)]);}break;}
case 'scan':await enqueue('scan',id,{test:d.test===true});break;
case 'schedule':result=await scheduleCandidates();break;
case 'candidate':{const status=z.enum(['eligible','excluded']).parse(d.status);await db().prepare("UPDATE auto_candidates SET status=? WHERE id=? AND used_at IS NULL AND selected_at IS NULL").bind(status,id).run();break}
case 'publishNow':{const job=await db().prepare("SELECT candidate_id,status FROM auto_post_jobs WHERE id=? AND post_id IS NULL").bind(id).first();if(!job||job.status==='excluded')throw new HttpError(409,'재시도할 수 없는 작업');if(job.status!=='queued'){await enqueue('publish',id);await db().prepare("UPDATE auto_candidates SET status='queued' WHERE id=?").bind(job.candidate_id).run();await db().prepare("UPDATE auto_post_jobs SET status='queued',last_error='' WHERE id=?").bind(id).run();}}await db().prepare("UPDATE worker_tasks SET run_at=? WHERE kind='publish' AND ref_id=? AND status='queued'").bind(Date.now(),id).run();await db().prepare("UPDATE auto_post_jobs SET scheduled_at=? WHERE id=? AND status='queued'").bind(Date.now(),id).run();break;
case 'excludeJob':{const j=await db().prepare('SELECT candidate_id FROM auto_post_jobs WHERE id=?').bind(id).first<{candidate_id:string}>();await db().batch([db().prepare("UPDATE worker_tasks SET status='cancelled',lease_token=NULL WHERE ref_id=? AND kind='publish' AND status IN ('queued','running')").bind(id),db().prepare("UPDATE auto_post_jobs SET status='excluded' WHERE id=? AND post_id IS NULL").bind(id)]);if(j)await db().prepare("UPDATE auto_candidates SET status='excluded' WHERE id=? AND used_at IS NULL").bind(j.candidate_id).run();break}
case 'shortCreate':result=await createShorts(user.userId,d);break;
case 'shortApprove':{const r=await db().prepare("UPDATE shorts_jobs SET approved_at=? WHERE id=? AND status='ready' AND EXISTS(SELECT 1 FROM shorts_outputs WHERE job_id=? AND qc_status='passed')").bind(Date.now(),id,id).run();if(!r.meta.changes)throw new HttpError(409,'QC 통과된 영상만 승인할 수 있습니다.');break}
case 'shortReject':case 'shortCancel':await db().batch([db().prepare("UPDATE shorts_jobs SET status='rejected' WHERE id=? AND status NOT IN ('published','scheduled')").bind(id),db().prepare("UPDATE worker_tasks SET status='cancelled',lease_token=NULL WHERE ref_id=? AND kind='render' AND status IN ('queued','running')").bind(id),db().prepare('DELETE FROM shorts_locks WHERE job_id=?').bind(id)]);break;
case 'shortRetry':{const j=await db().prepare("SELECT id,config FROM shorts_jobs WHERE id=? AND status='failed'").bind(id).first();if(!j)throw new HttpError(409,'실패 작업만 재시도 가능합니다.');const ids=(await db().prepare('SELECT post_id FROM shorts_job_posts WHERE job_id=? ORDER BY sequence').bind(id).all()).results.map(p=>p.post_id);result=await createShorts(user.userId,{postIds:ids,force:false,config:JSON.parse(String(j.config))});break}
case 'upload':result=await queueUpload(d);break;
case 'resetUpload':if(d.confirm!=='채널 중복 확인 완료')throw new HttpError(400,'채널 중복 확인이 필요합니다.');await db().prepare("UPDATE shorts_publications SET upload_session='',external_id='',error='' WHERE id=? AND status='failed'").bind(id).run();break;
case 'sync':await enqueue('sync',id,{},Date.now(),1);break;
case 'gmail':await enqueue('gmail',crypto.randomUUID(),{},Date.now(),1);break;
case 'mailApprove':result=await publishMail(id,{title:z.string().min(1).max(120).parse(d.title),body:z.string().min(1).max(30000).parse(d.body)});break;
case 'mailReject':{const row=await db().prepare('SELECT provider_message_id FROM email_ingest_messages WHERE id=? AND post_id IS NULL').bind(id).first();if(row)await db().batch([db().prepare("UPDATE email_ingest_messages SET status='rejected' WHERE id=? AND post_id IS NULL").bind(id),taskStatement('gmailLabel',id,{providerId:row.provider_message_id,outcome:'ERROR',mailbox:(await ops()).config.gmailMailbox})]);break;}
case 'mailLabelRetry':{const m=await db().prepare('SELECT provider_message_id,status,post_id FROM email_ingest_messages WHERE id=?').bind(id).first();if(!m)throw new HttpError(404,'메일 없음');const pending=await db().prepare("SELECT id FROM worker_tasks WHERE kind='gmailLabel' AND ref_id=? AND status IN ('queued','running')").bind(id).first();if(!pending)await enqueue('gmailLabel',id,{providerId:m.provider_message_id,outcome:m.post_id?'DONE':m.status==='rejected'?'ERROR':'REVIEW',mailbox:(await ops()).config.gmailMailbox});break;}
case 'postExclude':await db().prepare('UPDATE posts SET short_excluded=? WHERE id=?').bind(d.excluded?1:0,id).run();break;
default:throw new HttpError(400,'지원하지 않는 작업')}
await event(id||'admin',action,user.userId);return Response.json(result)});
