import {sqliteTable,text,integer,index,primaryKey,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const posts=sqliteTable('posts',{id:text('id').primaryKey(),owner:text('owner').notNull(),nickname:text('nickname').notNull(),title:text('title').notNull(),category:text('category').notNull(),body:text('body').notNull(),source:text('source').notNull().default(''),systemAuthor:text('system_author'),sourceCandidate:text('source_candidate'),shortExcluded:integer('short_excluded').notNull().default(0),thumbnail:text('thumbnail').notNull().default(''),createdAt:integer('created_at').notNull(),hidden:integer('hidden').notNull().default(0),views:integer('views').notNull().default(0)},t=>[index('posts_feed').on(t.hidden,t.createdAt),index('posts_category').on(t.category,t.hidden,t.createdAt)]);
export const media=sqliteTable('media',{id:text('id').primaryKey(),owner:text('owner').notNull(),type:text('type').notNull(),size:integer('size').notNull(),createdAt:integer('created_at').notNull()});
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),postId:text('post_id').notNull().references(()=>posts.id),owner:text('owner').notNull(),nickname:text('nickname').notNull(),body:text('body').notNull(),origin:text('origin').notNull().default('local'),sourceId:text('source_id'),externalCommentId:text('external_comment_id'),importedAt:integer('imported_at'),createdAt:integer('created_at').notNull()},t=>[index('comments_post').on(t.postId,t.createdAt)]);
export const likes=sqliteTable('likes',{postId:text('post_id').notNull().references(()=>posts.id),owner:text('owner').notNull()},t=>[primaryKey({columns:[t.postId,t.owner]})]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),postId:text('post_id').notNull().references(()=>posts.id),owner:text('owner').notNull(),reason:text('reason').notNull(),createdAt:integer('created_at').notNull()},t=>[index('reports_post').on(t.postId)]);
export const quotas=sqliteTable('quotas',{id:text('id').primaryKey(),count:integer('count').notNull()});




export const settingsTable=sqliteTable('settings',{id:text('id').primaryKey(),value:text('value').notNull(),revision:integer('revision').notNull().default(0)});
export const members=sqliteTable('members',{owner:text('owner').primaryKey(),nickname:text('nickname').notNull().unique(),points:integer('points').notNull().default(0),createdAt:integer('created_at').notNull()});
export const purchases=sqliteTable('purchases',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>members.owner),target:text('target').notNull(),postId:text('post_id').notNull().references(()=>posts.id),mediaId:text('media_id'),cost:integer('cost').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('purchase_owner_target').on(t.owner,t.target)]);
export const ledger=sqliteTable('ledger',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>members.owner),delta:integer('delta').notNull(),reason:text('reason').notNull(),createdAt:integer('created_at').notNull()},t=>[index('ledger_member_time').on(t.owner,t.createdAt)]);
export const grants=sqliteTable('grants',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>members.owner),amount:integer('amount').notNull(),reason:text('reason').notNull(),actor:text('actor').notNull(),createdAt:integer('created_at').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),createdAt:integer('created_at').notNull()});
export const postViews=sqliteTable('post_views',{postId:text('post_id').notNull().references(()=>posts.id),viewer:text('viewer').notNull(),day:text('day').notNull()},t=>[primaryKey({columns:[t.postId,t.viewer,t.day]})]);
export const previews=sqliteTable('previews',{id:text('id').primaryKey(),url:text('url').notNull().unique(),title:text('title').notNull(),description:text('description').notNull(),imageId:text('image_id'),createdAt:integer('created_at').notNull()});


// V3 integration tables. JSON configurations preserve per-source and per-job overrides.
export const auto_sources=sqliteTable('auto_sources',{id:text('id').primaryKey(),name:text('name').notNull(),config:text('config').notNull(),enabled:integer('enabled').notNull(),tested_at:integer('tested_at'),last_run_at:integer('last_run_at'),last_success_at:integer('last_success_at'),last_error:text('last_error').notNull(),created_at:integer('created_at').notNull(),updated_at:integer('updated_at').notNull()});
export const auto_candidates=sqliteTable('auto_candidates',{id:text('id').primaryKey(),source_id:text('source_id').notNull(),external_id:text('external_id').notNull(),canonical_url:text('canonical_url').notNull(),title:text('title').notNull(),detail:text('detail').notNull(),published_at:integer('published_at'),first_seen_at:integer('first_seen_at').notNull(),first_seen_run_id:text('first_seen_run_id').notNull(),last_seen_at:integer('last_seen_at').notNull(),selected_at:integer('selected_at'),used_at:integer('used_at'),score:integer('score').notNull(),metrics:text('metrics').notNull(),title_hash:text('title_hash').notNull(),body_hash:text('body_hash').notNull(),media_hash:text('media_hash').notNull(),duplicate_of:text('duplicate_of').notNull(),status:text('status').notNull(),reason:text('reason').notNull()},t=>[uniqueIndex('source_external').on(t.source_id,t.external_id),index('candidate_pool').on(t.status,t.first_seen_at),index('candidate_title').on(t.title_hash),index('candidate_body').on(t.body_hash)]);
export const crawl_runs=sqliteTable('crawl_runs',{id:text('id').primaryKey(),source_id:text('source_id').notNull(),status:text('status').notNull(),counts:text('counts').notNull(),error:text('error').notNull(),started_at:integer('started_at').notNull(),finished_at:integer('finished_at')});
export const auto_post_jobs=sqliteTable('auto_post_jobs',{id:text('id').primaryKey(),candidate_id:text('candidate_id').notNull(),source_id:text('source_id').notNull(),scheduled_at:integer('scheduled_at').notNull(),day:text('day').notNull(),status:text('status').notNull(),attempts:integer('attempts').notNull(),last_error:text('last_error').notNull(),post_id:text('post_id')},t=>[uniqueIndex('candidate_job').on(t.candidate_id),index('source_daily').on(t.source_id,t.day),index('auto_due').on(t.status,t.scheduled_at)]);
export const ops_settings=sqliteTable('ops_settings',{id:text('id').primaryKey(),value:text('value').notNull(),revision:integer('revision').notNull()});
export const worker_tasks=sqliteTable('worker_tasks',{id:text('id').primaryKey(),kind:text('kind').notNull(),ref_id:text('ref_id').notNull(),payload:text('payload').notNull(),status:text('status').notNull(),attempts:integer('attempts').notNull(),max_attempts:integer('max_attempts').notNull(),run_at:integer('run_at').notNull(),lease_token:text('lease_token'),lease_until:integer('lease_until'),error:text('error').notNull(),created_at:integer('created_at').notNull(),updated_at:integer('updated_at').notNull()},t=>[index('task_due').on(t.status,t.run_at),index('task_ref').on(t.kind,t.ref_id,t.status)]);
export const worker_health=sqliteTable('worker_health',{id:text('id').primaryKey(),last_seen_at:integer('last_seen_at').notNull(),capabilities:text('capabilities').notNull()});
export const job_events=sqliteTable('job_events',{id:text('id').primaryKey(),job_id:text('job_id').notNull(),stage:text('stage').notNull(),message:text('message').notNull(),created_at:integer('created_at').notNull()},t=>[index('events_job').on(t.job_id,t.created_at)]);
export const shorts_jobs=sqliteTable('shorts_jobs',{id:text('id').primaryKey(),status:text('status').notNull(),created_by:text('created_by').notNull(),config:text('config').notNull(),plan:text('plan').notNull(),progress:integer('progress').notNull(),error:text('error').notNull(),retry_count:integer('retry_count').notNull(),approved_at:integer('approved_at'),created_at:integer('created_at').notNull(),completed_at:integer('completed_at')});
export const shorts_job_posts=sqliteTable('shorts_job_posts',{id:text('id').primaryKey(),job_id:text('job_id').notNull(),post_id:text('post_id').notNull(),sequence:integer('sequence').notNull()},t=>[index('short_post').on(t.post_id)]);
export const shorts_locks=sqliteTable('shorts_locks',{post_id:text('post_id').primaryKey(),job_id:text('job_id').notNull()});
export const shorts_assets=sqliteTable('shorts_assets',{id:text('id').primaryKey(),type:text('type').notNull(),name:text('name').notNull(),storage_key:text('storage_key').notNull(),mime_type:text('mime_type').notNull(),license_note:text('license_note').notNull(),active:integer('active').notNull(),created_at:integer('created_at').notNull()});
export const shorts_outputs=sqliteTable('shorts_outputs',{id:text('id').primaryKey(),job_id:text('job_id').notNull(),storage_key:text('storage_key').notNull(),width:integer('width').notNull(),height:integer('height').notNull(),fps:integer('fps').notNull(),duration_ms:integer('duration_ms').notNull(),file_size:integer('file_size').notNull(),audio_mode:text('audio_mode').notNull(),qc_status:text('qc_status').notNull(),qc_json:text('qc_json').notNull(),created_at:integer('created_at').notNull()},t=>[uniqueIndex('output_job').on(t.job_id)]);
export const shorts_publications=sqliteTable('shorts_publications',{id:text('id').primaryKey(),job_id:text('job_id').notNull(),external_id:text('external_id').notNull(),privacy:text('privacy').notNull(),status:text('status').notNull(),scheduled_at:integer('scheduled_at'),published_at:integer('published_at'),metadata:text('metadata').notNull(),upload_session:text('upload_session').notNull(),last_synced_at:integer('last_synced_at'),created_at:integer('created_at').notNull(),error:text('error').notNull()},t=>[uniqueIndex('publication_job').on(t.job_id)]);
export const shorts_metrics=sqliteTable('shorts_metrics',{id:text('id').primaryKey(),publication_id:text('publication_id').notNull(),measured_at:integer('measured_at').notNull(),views:integer('views').notNull(),likes:integer('likes').notNull(),comments:integer('comments').notNull(),raw:text('raw').notNull()},t=>[index('metrics_publication').on(t.publication_id,t.measured_at)]);
export const email_ingest_messages=sqliteTable('email_ingest_messages',{id:text('id').primaryKey(),provider_message_id:text('provider_message_id').notNull(),message_id:text('message_id').notNull(),subject:text('subject').notNull(),received_at:integer('received_at').notNull(),content_hash:text('content_hash').notNull(),parsed_title:text('parsed_title').notNull(),parsed_body:text('parsed_body').notNull(),privacy_status:text('privacy_status').notNull(),privacy_reasons:text('privacy_reasons').notNull(),status:text('status').notNull(),post_id:text('post_id'),error:text('error').notNull(),created_at:integer('created_at').notNull()},t=>[uniqueIndex('mail_message').on(t.message_id),uniqueIndex('mail_content').on(t.content_hash)]);
export const system_profiles=sqliteTable('system_profiles',{id:text('id').primaryKey(),display_name:text('display_name').notNull()});
