import {requiredFields} from './modes.mjs';
import {validEvidence,sourceIdentity} from './validation.mjs';
import {z} from 'zod';import {db,HttpError} from '../server';import {ops,enqueue,event,taskStatement,type Row} from './server';import {sourceSchema} from './config';import {fingerprint,normalizedTitle,selectCandidates,scheduleSlots,koreanDay,privacyScan,type Candidate} from './policy';
export const detailSchema=z.object({policyIdentity:z.string().optional(),collectionMode:z.string().optional(),availableFields:z.array(z.string()).optional(),requiredFields:z.array(z.string()).optional(),author:z.string().optional(),title:z.string().min(1).max(120),externalId:z.string().min(1).max(200),url:z.string().url().max(2000),publishedAt:z.number().nullable().default(null),metrics:z.object({views:z.number().min(0),likes:z.number().min(0),comments:z.number().min(0)}),blocks:z.array(z.union([z.object({type:z.literal('text'),text:z.string().max(30000)}),z.object({type:z.enum(['image','video']),url:z.string().url().max(4000)}),z.object({type:z.literal('youtube'),videoId:z.string().regex(/^[\w-]{11}$/)}),z.object({type:z.literal('link'),url:z.string().url().refine(v=>v.startsWith('https://'))})])).max(100),comments:z.array(z.object({id:z.string().max(200),text:z.string().max(2000)})).max(5),mediaHash:z.string().max(100).default('')});
export async function acceptScan(sourceId:string,raw:unknown,test=false,validation?:unknown){const row=await db().prepare('SELECT config FROM auto_sources WHERE id=?').bind(sourceId).first<{config:string}>();if(!row)throw new HttpError(404,'소스 없음');const s=sourceSchema.parse(JSON.parse(row.config)),items=z.array(detailSchema).max(s.scanLimit).parse(raw),now=Date.now(),run=crypto.randomUUID();const verified=test&&validEvidence(s,validation);const counts={validation:test?validation:undefined,scanned:items.length,new:0,existing:0,duplicate:0,filtered:0,valid:0,selected:0};const cfg=(await ops()).config;
await db().prepare("INSERT INTO crawl_runs(id,source_id,status,counts,error,started_at,finished_at) VALUES(?,?,'running','{}','',?,NULL)").bind(run,sourceId,now).run();
for(const item of items){const url=new URL(item.url);if(url.hostname!==new URL(s.url).hostname)continue;url.hash='';const canonical=url.href;const old=await db().prepare('SELECT id,used_at,selected_at,detail,status FROM auto_candidates WHERE source_id=? AND (external_id=? OR canonical_url=?)').bind(sourceId,item.externalId,canonical).first();const score=item.metrics.likes*s.weights.likes+item.metrics.comments*s.weights.comments+item.metrics.views*s.weights.views;
if(old){counts.existing++;await db().prepare('UPDATE auto_candidates SET last_seen_at=?,score=?,metrics=? WHERE id=?').bind(now,score,JSON.stringify(item.metrics),old.id).run();if(!old.used_at&&!old.selected_at&&item.policyIdentity&&['eligible','filtered','review_required'].includes(String(old.status))){const text=item.blocks.filter(b=>b.type==='text').map(b=>b.text).join('\n'),privacy=privacyScan(text+'\n'+item.comments.map(c=>c.text).join('\n'),cfg.privateDenylist);const filtered=requiredFields(s).some(f=>!item.availableFields?.includes(f))||s.denyWords.some(v=>(item.title+text).includes(v))||item.metrics.views<s.minViews||item.metrics.likes<s.minLikes||item.metrics.comments<s.minComments;await db().prepare('UPDATE auto_candidates SET detail=?,status=?,reason=? WHERE id=? AND used_at IS NULL AND selected_at IS NULL').bind(JSON.stringify(item),filtered?'filtered':privacy.status==='review_required'?'review_required':'eligible',filtered?'source filter':privacy.reasons.join(','),old.id).run()}continue}
const titleHash=await fingerprint(normalizedTitle(item.title)),bodyText=item.blocks.filter(b=>b.type==='text').map(b=>b.text).join('\n'),bodyHash=bodyText.length>20?await fingerprint(bodyText.replace(/\s/g,'')):'';
const duplicate=await db().prepare("SELECT id FROM auto_candidates WHERE title_hash=? OR (body_hash<>'' AND body_hash=?) OR (media_hash<>'' AND media_hash=?) LIMIT 1").bind(titleHash,bodyHash,item.mediaHash).first<{id:string}>();
const privacy=privacyScan(bodyText+'\n'+item.comments.map(c=>c.text).join('\n'),cfg.privateDenylist);const missing=item.collectionMode?requiredFields(s).filter(f=>!item.availableFields?.includes(f)):[];const filtered=missing.length>0||s.denyWords.some(v=>(item.title+bodyText).includes(v))||item.metrics.views<s.minViews||item.metrics.likes<s.minLikes||item.metrics.comments<s.minComments;
const status=duplicate?'duplicate':filtered?'filtered':privacy.status==='review_required'?'review_required':'eligible';counts.new++;if(duplicate)counts.duplicate++;else if(filtered)counts.filtered++;else if(status==='eligible')counts.valid++;
await db().prepare('INSERT INTO auto_candidates(id,source_id,external_id,canonical_url,title,detail,published_at,first_seen_at,first_seen_run_id,last_seen_at,selected_at,used_at,score,metrics,title_hash,body_hash,media_hash,duplicate_of,status,reason) VALUES(?,?,?,?,?,?,?,?,?,?,NULL,NULL,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),sourceId,item.externalId,canonical,(s.prefix+item.title).slice(0,120),JSON.stringify(item),item.publishedAt,now,run,now,score,JSON.stringify(item.metrics),titleHash,bodyHash,item.mediaHash,duplicate?.id||'',status,duplicate?'cross-source duplicate':filtered?(missing.length?'REQUIRED_FIELDS_MISSING: '+missing.join(', '):'source filter'):privacy.reasons.join(',')).run()}
await db().batch([db().prepare("UPDATE crawl_runs SET status='completed',counts=?,finished_at=? WHERE id=?").bind(JSON.stringify(counts),Date.now(),run),db().prepare('UPDATE auto_sources SET last_run_at=?,last_success_at=?,last_error=?,tested_at=CASE WHEN ? THEN ? ELSE tested_at END WHERE id=?').bind(now,now,test&&!verified?'필수 필드 확보 여부 재검증 필요':items.length?'':'SELECTOR_MISMATCH: 후보 0개',test?1:0,verified?now:null,sourceId)]);
if(test&&!verified)await db().prepare("UPDATE auto_sources SET enabled=0,config=json_set(config,'$.enabled',json('false')) WHERE id=?").bind(sourceId).run();
if(verified&&(validation as {version?:number})?.version===3)await db().prepare("UPDATE auto_sources SET config=json_set(config,'$.resolvedMode',?) WHERE id=?").bind((validation as {mode:string}).mode,sourceId).run();
await event(sourceId,'scan_completed',JSON.stringify(counts));if(!test&&!cfg.paused&&s.enabled)await scheduleCandidates(sourceId,run);return {run,counts}}
async function sourceVerified(id:string,s:unknown){const r=await db().prepare("SELECT counts FROM crawl_runs WHERE source_id=? AND status='completed' AND json_extract(counts,'$.validation') IS NOT NULL ORDER BY started_at DESC LIMIT 1").bind(id).first<{counts:string}>();return validEvidence(s,r?JSON.parse(r.counts).validation:null)}
export async function scheduleCandidates(sourceId?:string,runId?:string){const now=Date.now();await db().prepare("INSERT OR IGNORE INTO worker_health(id,last_seen_at,capabilities) VALUES('schedule-lock',0,'{}')").run();const lock=await db().prepare("UPDATE worker_health SET last_seen_at=? WHERE id='schedule-lock' AND last_seen_at<? RETURNING id").bind(now,now-60000).first();if(!lock)return {scheduled:0,busy:true};try{return await scheduleLocked(sourceId,runId)}finally{await db().prepare("UPDATE worker_health SET last_seen_at=0 WHERE id='schedule-lock' AND last_seen_at=?").bind(now).run()}}
async function scheduleLocked(sourceId?:string,runId?:string){const {config}=await ops(),now=Date.now(),day=koreanDay(now);const sources=(await db().prepare('SELECT * FROM auto_sources WHERE enabled=1'+(sourceId?' AND id=?':'')).bind(...(sourceId?[sourceId]:[])).all<Row>()).results;const chosen:Candidate[]=[];
for(const row of sources){const s=sourceSchema.parse(JSON.parse(String(row.config)));if(!await sourceVerified(String(row.id),s))continue;const used=await db().prepare("SELECT COUNT(*) n FROM auto_post_jobs WHERE source_id=? AND day=? AND status<>'excluded'").bind(row.id,day).first<{n:number}>();const items=(await db().prepare("SELECT * FROM auto_candidates WHERE source_id=? AND status='eligible' AND selected_at IS NULL AND used_at IS NULL ORDER BY score DESC LIMIT 300").bind(row.id).all()).results;const run=runId||(await db().prepare("SELECT id FROM crawl_runs WHERE source_id=? AND status='completed' ORDER BY started_at DESC LIMIT 1").bind(row.id).first<{id:string}>())?.id||'';chosen.push(...selectCandidates(items.filter(item=>{try{const d=JSON.parse(String(item.detail));return !s.resolvedMode&&!s.requiredFields&&s.collectionMode==='AUTO'||d.policyIdentity===sourceIdentity(s)}catch{return false}}) as unknown as Candidate[],s,run,now,used?.n||0))}
const latest=await db().prepare("SELECT MAX(scheduled_at) at FROM auto_post_jobs WHERE day=? AND status<>'excluded'").bind(day).first<{at:number|null}>();const slots=scheduleSlots(chosen,config.start,config.intervalMinutes,now);let scheduled=0;
for(let i=0;i<slots.length;i++){const {item}=slots[i];const at=Math.max(slots[i].at,(latest?.at||0)+(i+1)*config.intervalMinutes*60000),id=crypto.randomUUID();const changed=await db().prepare("UPDATE auto_candidates SET selected_at=?,status='queued' WHERE id=? AND selected_at IS NULL AND used_at IS NULL RETURNING id").bind(now,item.id).first();if(!changed)continue;
try{await db().batch([db().prepare("INSERT INTO auto_post_jobs(id,candidate_id,source_id,scheduled_at,day,status,attempts,last_error,post_id) VALUES(?,?,?,?,?,'queued',0,'',NULL)").bind(id,item.id,item.source_id,at,day),taskStatement('publish',id,{},at)]);scheduled++}catch(e){await db().prepare("UPDATE auto_candidates SET selected_at=NULL,status='eligible' WHERE id=? AND used_at IS NULL").bind(item.id).run();throw e}}
return {scheduled,windowWarning:slots.length*config.intervalMinutes>config.windowMinutes}}
export async function publishCandidate(jobId:string,raw:unknown){const {config}=await ops();if(config.paused)throw new HttpError(409,'긴급정지 중입니다.');const job=await db().prepare('SELECT j.*,c.title,c.detail,c.source_id,c.used_at FROM auto_post_jobs j JOIN auto_candidates c ON c.id=j.candidate_id WHERE j.id=?').bind(jobId).first<Row>();if(!job)throw new HttpError(404,'게시 작업 없음');if(job.status==='excluded')throw new HttpError(409,'제외된 작업');if(job.post_id||job.used_at)return {postId:job.post_id};const sourceRow=await db().prepare('SELECT config FROM auto_sources WHERE id=?').bind(job.source_id).first<{config:string}>();const source=sourceSchema.parse(JSON.parse(sourceRow!.config));if(!await sourceVerified(String(job.source_id),source))throw new HttpError(409,'수집 소스 재검증 필요');if(!source.enabled)throw new HttpError(409,'소스 OFF');const content=z.object({blocks:z.array(z.union([z.object({type:z.literal('text'),text:z.string().max(30000)}),z.object({type:z.enum(['image','video']),id:z.string().uuid()}),z.object({type:z.literal('youtube'),videoId:z.string().regex(/^[\w-]{11}$/)}),z.object({type:z.literal('link'),url:z.string().url().refine(v=>v.startsWith('https://'))})])).min(1).max(100),warnings:z.array(z.string()).default([])}).parse(raw);
const ids=content.blocks.filter(b=>'id'in b).map(b=>b.id);for(const id of ids){if(!await db().prepare("SELECT id FROM media WHERE id=? AND owner='system:auto'").bind(id).first())throw new HttpError(400,'미디어 검증 실패')}
if(content.warnings.length&&source.mediaFailure==='review_required'){await db().prepare("UPDATE auto_candidates SET status='review_required',reason=? WHERE id=?").bind(content.warnings.join(';'),job.candidate_id).run();await db().prepare("UPDATE auto_post_jobs SET status='review_required',last_error=? WHERE id=?").bind(content.warnings.join(';'),jobId).run();return {review:true}}
const detail=detailSchema.parse(JSON.parse(String(job.detail)));if((source.resolvedMode||source.requiredFields||source.collectionMode!=='AUTO')&&detail.policyIdentity!==sourceIdentity(source))throw new HttpError(409,'수집 방식 변경 후 다시 수집해야 합니다.');const missing=detail.collectionMode?requiredFields(source).filter(f=>f==='image'||f==='thumbnail'?!content.blocks.some(b=>b.type==='image'):f==='video'?!content.blocks.some(b=>b.type==='video'||b.type==='youtube'):!detail.availableFields?.includes(f)):[];if(missing.length)throw new HttpError(409,'게시 필수 항목 누락: '+missing.join(', '));const postId=jobId,now=Date.now();const profile='system:auto';const stm=[db().prepare("INSERT INTO system_profiles(id,display_name) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET display_name=excluded.display_name").bind(profile,config.authorName),db().prepare("INSERT OR IGNORE INTO posts(id,owner,nickname,title,category,body,source,thumbnail,created_at,system_author,source_candidate) VALUES(?,?,?,?,?,?,'',?,?,?,?)").bind(postId,profile,config.authorName,job.title,source.board,JSON.stringify(content.blocks),content.blocks.find(b=>b.type==='image')?'/api/media/'+(content.blocks.find(b=>b.type==='image') as {id:string}).id:'',now,profile,job.candidate_id)];
for(const [i,c]of detail.comments.slice(0,source.commentLimit).entries())stm.push(db().prepare("INSERT OR IGNORE INTO comments(id,post_id,owner,nickname,body,created_at,origin,source_id,external_comment_id,imported_at) VALUES(?,?,?,?,?,?,'imported',?,?,?)").bind(postId+'-comment-'+i,postId,profile,config.nicknames[crypto.getRandomValues(new Uint32Array(1))[0]%config.nicknames.length],c.text,now+i,job.source_id,c.id,now));
stm.push(db().prepare("UPDATE auto_candidates SET used_at=?,status='published' WHERE id=?").bind(now,job.candidate_id),db().prepare("UPDATE auto_post_jobs SET status='published',post_id=? WHERE id=?").bind(postId,jobId));await db().batch(stm);await event(jobId,'published');return {postId}}
export async function tick(){const now=Date.now();await db().prepare("INSERT OR IGNORE INTO worker_health(id,last_seen_at,capabilities) VALUES('scheduler',0,'{}')").run();const lock=await db().prepare("UPDATE worker_health SET last_seen_at=? WHERE id='scheduler' AND last_seen_at<? RETURNING id").bind(now,now-60000).first();if(!lock)return;const {config}=await ops();if(config.paused)return;const sources=(await db().prepare('SELECT * FROM auto_sources WHERE enabled=1 AND tested_at IS NOT NULL').all<Row>()).results;for(const row of sources){const s=sourceSchema.parse(JSON.parse(String(row.config)));if(!await sourceVerified(String(row.id),s)){await db().prepare("UPDATE auto_sources SET enabled=0,tested_at=NULL,config=json_set(config,'$.enabled',json('false')),last_error='강화된 수집 검증 필요' WHERE id=?").bind(row.id).run();continue;}if(now-Number(row.last_run_at||0)<s.intervalMinutes*60000)continue;const pending=await db().prepare("SELECT id FROM worker_tasks WHERE kind='scan' AND ref_id=? AND status IN ('queued','running')").bind(row.id).first();if(!pending){await enqueue('scan',String(row.id));await db().prepare('UPDATE auto_sources SET last_run_at=? WHERE id=?').bind(now,row.id).run()}}
if(config.gmailEnabled){const recent=await db().prepare("SELECT id FROM worker_tasks WHERE kind='gmail' AND (status IN ('queued','running') OR created_at>?)").bind(now-180000).first();if(!recent)await enqueue('gmail',crypto.randomUUID())}}
