export type Candidate={id:string;source_id:string;first_seen_at:number;first_seen_run_id:string;used_at:number|null;selected_at:number|null;score:number;status:string;published_at?:number|null};
export function selectCandidates<T extends Candidate>(items:T[],config:{maxAgeDays:number;preferNew:boolean;fallback:boolean;dailyLimit:number;selection:string},runId:string,now:number,already=0){const pool=items.filter(x=>!x.used_at&&!x.selected_at&&x.status==='eligible'&&now-x.first_seen_at<=config.maxAgeDays*86400000);const fresh=pool.filter(x=>x.first_seen_run_id===runId);const group=config.preferNew&&fresh.length?fresh:config.fallback||!config.preferNew?pool:[];return group.sort((a,b)=>config.selection==='newest'?b.first_seen_at-a.first_seen_at:b.score-a.score||b.first_seen_at-a.first_seen_at).slice(0,Math.max(0,config.dailyLimit-already))}
export function koreanDay(now=Date.now()){return new Date(now+9*3600000).toISOString().slice(0,10)}
export function scheduleSlots<T extends {source_id:string}>(items:T[],start='19:00',interval=3,now=Date.now()){const groups=new Map<string,T[]>();for(const x of items)groups.set(x.source_id,[...(groups.get(x.source_id)||[]),x]);const ordered:T[]=[];while([...groups.values()].some(g=>g.length))for(const g of groups.values())if(g.length)ordered.push(g.shift()!);const base=Date.parse(koreanDay(now)+'T'+start+':00+09:00');return ordered.map((item,i)=>({item,at:Math.max(base,now)+i*interval*60000}))}
export function normalizedTitle(v:string){return v.normalize('NFKC').toLowerCase().replace(/\[[^\]]*\]/g,'').replace(/[^\p{L}\p{N}]/gu,'')}
export async function fingerprint(v:string|Uint8Array){const b=typeof v==='string'?new TextEncoder().encode(v):v;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b as BufferSource)),n=>n.toString(16).padStart(2,'0')).join('')}
export function contentReviewScan(text:string,denylist:string[]=[]){const normalized=text.normalize('NFKC').toLowerCase(),reasons:string[]=[];const groups:[string,RegExp][]=[['정치 가능성',/(?:대통령|국회의원|국민의힘|민주당|정의당|조국혁신당|선거|탄핵|정권|좌파|우파|진보|보수|윤석열|이재명)/],['성별갈등 가능성',/(?:여혐|남혐|한남|한녀|메갈|워마드|페미(?:니스트|니즘)?|젠더갈등|성별갈등|맘충|퐁퐁남|도태남)/],['혐오·비하 가능성',/(?:혐오|짱깨|쪽바리|틀딱|급식충|장애인\s*비하|지역\s*비하|인종\s*차별|벌레충)/]];for(const [label,rule] of groups)if(rule.test(normalized))reasons.push(label);const matched=denylist.find(v=>v&&normalized.includes(v.normalize('NFKC').toLowerCase()));if(matched)reasons.push('사이트 주의어: '+matched);return {status:reasons.length?'review_required':'passed',reasons}}
export function privacyScan(text:string,denylist:string[]){if(typeof text!=='string'||!Array.isArray(denylist))throw Error('PRIVACY_SCAN_INVALID');const rules:[string,RegExp][]=[['email',/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/],['phone',/(?:\+82[- ]?|0)(?:1[016789]|2|[3-6]\d)[- .]?\d{3,4}[- .]?\d{4}/],['resident_id',/\b\d{6}[- ]?[1-8]\d{6}\b/],['financial_number',/\b\d{3,6}[- ]\d{2,6}[- ]\d{3,8}\b|\b\d{13,19}\b/],['secret',/\b(?:sk[-_][\w-]{16,}|AIza[\w-]{20,}|Bearer\s+[\w.-]{12,}|(?:api[_ -]?key|token|password|비밀번호)\s*[:=]\s*\S{5,})/i],['address',/(?:[가-힣]+(?:시|군|구)\s+){1,3}[가-힣0-9]+(?:로|길|동)\s*\d+/]];const found=rules.filter(([,r])=>r.test(text)).map(([name])=>name);if(denylist.some(v=>v&&text.toLowerCase().includes(v.toLowerCase())))found.push('private_denylist');return {status:found.length?'review_required':'passed',reasons:found}}
export function stripMail(text:string){return text.split(/\n(?:On .+wrote:|보낸 사람:|From:|_{4,}|-{4,}|수신거부|Unsubscribe)/i)[0].replace(/https?:\/\/\S+(?:utm_|tracking|unsubscribe)\S*/gi,'').replace(/\n>[\s\S]*/,'').replace(/\n{3,}/g,'\n\n').trim()}
