export type Candidate={id:string;source_id:string;first_seen_at:number;first_seen_run_id:string;used_at:number|null;selected_at:number|null;score:number;status:string;published_at?:number|null};
export function selectCandidates<T extends Candidate>(items:T[],config:{maxAgeDays:number;preferNew:boolean;fallback:boolean;dailyLimit:number;selection:string},runId:string,now:number,already=0){const pool=items.filter(x=>!x.used_at&&!x.selected_at&&x.status==='eligible'&&now-x.first_seen_at<=config.maxAgeDays*86400000);const fresh=pool.filter(x=>x.first_seen_run_id===runId);const group=config.preferNew&&fresh.length?fresh:config.fallback||!config.preferNew?pool:[];return group.sort((a,b)=>config.selection==='newest'?b.first_seen_at-a.first_seen_at:b.score-a.score||b.first_seen_at-a.first_seen_at).slice(0,Math.max(0,config.dailyLimit-already))}
export function koreanDay(now=Date.now()){return new Date(now+9*3600000).toISOString().slice(0,10)}
export function scheduleSlots<T extends {source_id:string}>(items:T[],start='19:00',interval=3,now=Date.now()){const groups=new Map<string,T[]>();for(const x of items)groups.set(x.source_id,[...(groups.get(x.source_id)||[]),x]);const ordered:T[]=[];while([...groups.values()].some(g=>g.length))for(const g of groups.values())if(g.length)ordered.push(g.shift()!);const base=Date.parse(koreanDay(now)+'T'+start+':00+09:00');return ordered.map((item,i)=>({item,at:Math.max(base,now)+i*interval*60000}))}
export function normalizedTitle(v:string){return v.normalize('NFKC').toLowerCase().replace(/\[[^\]]*\]/g,'').replace(/[^\p{L}\p{N}]/gu,'')}
export async function fingerprint(v:string|Uint8Array){const b=typeof v==='string'?new TextEncoder().encode(v):v;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b as BufferSource)),n=>n.toString(16).padStart(2,'0')).join('')}
export function contentReviewScan(text:string,denylist:string[]=[]){const normalized=text.normalize('NFKC').toLowerCase(),reasons:string[]=[];const groups:[string,RegExp][]=[['정치 가능성',/(?:대통령|국회의원|국민의힘|민주당|정의당|조국혁신당|선거|탄핵|정권|좌파|우파|진보|보수|윤석열|이재명)/],['성별갈등 가능성',/(?:여혐|남혐|한남|한녀|메갈|워마드|페미(?:니스트|니즘)?|젠더갈등|성별갈등|맘충|퐁퐁남|도태남)/],['혐오·비하 가능성',/(?:혐오|짱깨|쪽바리|틀딱|급식충|장애인\s*비하|지역\s*비하|인종\s*차별|벌레충)/]];for(const [label,rule] of groups)if(rule.test(normalized))reasons.push(label);const matched=denylist.find(v=>v&&normalized.includes(v.normalize('NFKC').toLowerCase()));if(matched)reasons.push('사이트 주의어: '+matched);return {status:reasons.length?'review_required':'passed',reasons}}
export function privacyScan(text:string,denylist:string[]){if(typeof text!=='string'||!Array.isArray(denylist))throw Error('PRIVACY_SCAN_INVALID');const rules:[string,RegExp][]=[['email',/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/],['phone',/(?:\+82[- ]?|0)(?:1[016789]|2|[3-6]\d)[- .]?\d{3,4}[- .]?\d{4}/],['resident_id',/\b\d{6}[- ]?[1-8]\d{6}\b/],['financial_number',/\b\d{3,6}[- ]\d{2,6}[- ]\d{3,8}\b|\b\d{13,19}\b/],['secret',/\b(?:sk[-_][\w-]{16,}|AIza[\w-]{20,}|Bearer\s+[\w.-]{12,}|(?:api[_ -]?key|token|password|비밀번호)\s*[:=]\s*\S{5,})/i],['address',/(?:[가-힣]+(?:시|군|구)\s+){1,3}[가-힣0-9]+(?:로|길|동)\s*\d+/]];const found=rules.filter(([,r])=>r.test(text)).map(([name])=>name);if(denylist.some(v=>v&&text.toLowerCase().includes(v.toLowerCase())))found.push('private_denylist');return {status:found.length?'review_required':'passed',reasons:found}}
export function stripMail(text:string){return text.split(/\n(?:On .+wrote:|보낸 사람:|From:|_{4,}|-{4,}|수신거부|Unsubscribe)/i)[0].replace(/https?:\/\/\S+(?:utm_|tracking|unsubscribe)\S*/gi,'').replace(/\n>[\s\S]*/,'').replace(/\n{3,}/g,'\n\n').trim()}

// Economy reports are published verbatim; only clearly sensitive personal data blocks publishing.
// Company names, tickers, prices, market caps, huge numbers, agency addresses, public phone numbers and URLs must pass.
const PERSONAL_MAIL=/[\w.+-]+@(?:gmail\.com|googlemail\.com|naver\.com|daum\.net|hanmail\.net|kakao\.com|nate\.com|outlook\.com|hotmail\.com|live\.com|yahoo\.com|yahoo\.co\.kr|icloud\.com|proton\.me|protonmail\.com)(?![\w-])/i;
const MOBILE=/(?<![\d,.])(?:\+82[- ]?0?1[016789]|01[016789])[- .]?\d{3,4}[- .]?\d{4}(?!\d)/;
const ACCOUNT=/(?:계좌(?:번호)?|입금|송금|예금주|account\s*(?:no\.?|number)?)[^\n]{0,24}?(?<![\d-])\d{2,6}(?:-\d{2,8}){1,3}(?![\d-])|(?:국민|신한|우리|하나|농협|기업|카카오뱅크|토스뱅크|케이뱅크|새마을|우체국|SC제일|수협|부산|대구|광주|전북|경남|제주)\s*(?:은행)?\s*:?\s*(?<![\d-])\d{2,6}-\d{2,8}-\d{2,8}(?:-\d{1,4})?(?![\d-])/i;
const SECRET=/(?<![\w-])(?:sk-[\w-]{20,}|AIza[\w-]{30,}|AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9]{30,}|xox[abprs]-[\w-]{10,}|Bearer\s+[A-Za-z0-9._~+\/-]{16,}=*)|(?:api[_ -]?key|secret|access[_ -]?token|refresh[_ -]?token|password|passwd|비밀번호|패스워드)\s*[:=]\s*["']?[A-Za-z0-9_\-.\/+=!@#$%^&*]{8,}/i;
function validResidentId(text:string){for(const m of text.matchAll(/(?<![\d-])(\d{2})(\d{2})(\d{2})[- ]([1-8])\d{6}(?![\d-])/g)){const month=Number(m[2]),day=Number(m[3]);if(month>=1&&month<=12&&day>=1&&day<=31)return true}return /(?:주민(?:등록)?\s*번호|RRN)[^\n]{0,12}?(?<!\d)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])[1-8]\d{6}(?!\d)/i.test(text)}
export function economyPrivacyScan(text:string,denylist:string[]=[]){if(typeof text!=='string')throw Error('PRIVACY_SCAN_INVALID');const found:string[]=[];if(validResidentId(text))found.push('resident_id');if(MOBILE.test(text))found.push('personal_phone');if(PERSONAL_MAIL.test(text))found.push('personal_email');if(ACCOUNT.test(text))found.push('bank_account');if(SECRET.test(text))found.push('secret');const lower=text.toLowerCase();if(denylist.some(v=>v&&lower.includes(v.toLowerCase())))found.push('private_denylist');return {status:found.length?'review_required':'passed',reasons:found}}
