import {sourceIdentity} from './validation.mjs';
import {env} from 'cloudflare:workers';
import {db,HttpError} from '../server';
import {opsSchema,defaultOps,type OpsConfig} from './config';
export type Row=Record<string,string|number|null>;
export async function ops(){const r=await db().prepare("SELECT value,revision FROM ops_settings WHERE id='main'").first<{value:string;revision:number}>();const saved=r?JSON.parse(r.value):defaultOps;const config=opsSchema.parse({...saved,...(env.SITE_NAME?{siteName:env.SITE_NAME}:{}),...(env.SITE_URL?{siteUrl:env.SITE_URL}:{})});return {config:config.authorName==='아지트 소식'?{...config,authorName:'꿀잼픽'}:config,revision:r?.revision||0}}
export async function event(job:string,stage:string,message=''){await db().prepare('INSERT INTO job_events(id,job_id,stage,message,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),job,stage,message.slice(0,2000),Date.now()).run()}
export function taskStatement(kind:string,ref:string,payload:unknown={},at=Date.now(),max=3){const id=crypto.randomUUID(),now=Date.now();return db().prepare("INSERT INTO worker_tasks(id,kind,ref_id,payload,status,attempts,max_attempts,run_at,lease_token,lease_until,error,created_at,updated_at) VALUES(?,?,?,?,'queued',0,?,?,NULL,NULL,'',?,?)").bind(id,kind,ref,JSON.stringify(payload),max,at,now,now)}
export async function enqueue(kind:string,ref:string,payload:unknown={},at=Date.now(),max=3){await taskStatement(kind,ref,payload,at,max).run()}
export async function workerAuth(req:Request){const key=env.WORKER_TOKEN;if(!key||key.length<32)throw new HttpError(503,'작업자 인증 설정이 필요합니다.');const a=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(req.headers.get('authorization')||''));const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('Bearer '+key));let diff=0;const aa=new Uint8Array(a),bb=new Uint8Array(b);for(let i=0;i<aa.length;i++)diff|=aa[i]^bb[i];if(diff!==0)throw new HttpError(401,'작업자 인증 실패');}
export async function lease(id:string,token:string){const row=await db().prepare("SELECT * FROM worker_tasks WHERE id=? AND lease_token=? AND status='running' AND lease_until>?").bind(id,token,Date.now()).first<Row>();if(!row)throw new HttpError(409,'작업 임대가 만료됐거나 취소됐습니다.');return row}
export async function claim(worker:string,capabilities:unknown){const now=Date.now(),{config}=await ops();await db().prepare('INSERT INTO worker_health(id,last_seen_at,capabilities) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET last_seen_at=excluded.last_seen_at,capabilities=excluded.capabilities').bind(worker,now,JSON.stringify(capabilities)).run();await db().prepare("UPDATE worker_tasks SET status=CASE WHEN attempts<max_attempts THEN 'queued' ELSE 'failed' END,lease_token=NULL,error='WORKER_LEASE_EXPIRED',updated_at=? WHERE status='running' AND lease_until<?").bind(now,now).run();await db().prepare("UPDATE shorts_jobs SET status='failed',error='WORKER_LEASE_EXPIRED' WHERE id IN (SELECT ref_id FROM worker_tasks WHERE kind='render' AND status='failed' AND error='WORKER_LEASE_EXPIRED') AND status NOT IN ('ready','published','scheduled','rejected')").run();await db().prepare("DELETE FROM shorts_locks WHERE job_id IN (SELECT id FROM shorts_jobs WHERE status='failed')").run();const token=crypto.randomUUID();const row=await db().prepare("UPDATE worker_tasks SET status='running',lease_token=?,lease_until=?,attempts=attempts+1,updated_at=? WHERE id=(SELECT id FROM worker_tasks WHERE status='queued' AND run_at<=? AND (?=0 OR kind NOT IN ('scan','publish','gmail') OR (kind='scan' AND json_extract(payload,'$.test')=1)) ORDER BY run_at,created_at LIMIT 1) RETURNING *").bind(token,now+180000,now,now,config.paused?1:0).first<Row>();if(!row)return null;const payload=await taskPayload(row,config);await event(String(row.ref_id),'claimed');return {...row,payload,config}}
export async function taskPayload(task:Row,config:OpsConfig){const ref=String(task.ref_id);if(task.kind==='scan'){const source=await db().prepare('SELECT * FROM auto_sources WHERE id=?').bind(ref).first<Row>();if(!source)throw new HttpError(404,'소스 없음');const saved=JSON.parse(String(task.payload));await db().prepare('UPDATE worker_tasks SET payload=? WHERE id=? AND lease_token=?').bind(JSON.stringify({...saved,sourceIdentity:sourceIdentity(JSON.parse(String(source.config)))}),task.id,task.lease_token).run();return {source:{...JSON.parse(String(source.config)),id:source.id},test:saved.test===true}}
if(task.kind==='publish'){const j=await db().prepare('SELECT * FROM auto_post_jobs WHERE id=?').bind(ref).first<Row>();const c=j?await db().prepare('SELECT * FROM auto_candidates WHERE id=?').bind(j.candidate_id).first<Row>():null;const source=c?await db().prepare('SELECT config FROM auto_sources WHERE id=?').bind(c.source_id).first<{config:string}>():null;return {job:j,candidate:c?{...c,detail:JSON.parse(String(c.detail))}:null,source:source?JSON.parse(source.config):null}}
if(task.kind==='render'){const job=await db().prepare('SELECT * FROM shorts_jobs WHERE id=?').bind(ref).first<Row>();const p=await db().prepare('SELECT p.* FROM posts p JOIN shorts_job_posts j ON j.post_id=p.id WHERE j.job_id=? ORDER BY j.sequence').bind(ref).all<Row>();const list=[];for(const post of p.results){const [comments,feed]=await Promise.all([db().prepare('SELECT body FROM comments WHERE post_id=? ORDER BY created_at LIMIT 3').bind(post.id).all(),db().prepare("SELECT p.id,p.title,p.category,p.nickname,p.created_at,p.views,(SELECT COUNT(*) FROM likes WHERE post_id=p.id) likes,(SELECT COUNT(*) FROM comments WHERE post_id=p.id) comments FROM posts p WHERE p.hidden=0 AND p.category=? ORDER BY CASE WHEN p.id=? THEN 0 ELSE 1 END,p.created_at DESC LIMIT 4").bind(post.category,post.id).all()]);const blocks=JSON.parse(String(post.body));const ids=blocks.filter((b:{id?:string})=>b.id).map((b:{id:string})=>b.id);const media=ids.length?(await db().prepare('SELECT * FROM media WHERE id IN ('+ids.map(()=>'?').join(',')+')').bind(...ids).all()).results:[];list.push({...post,blocks,comments:comments.results,media,feed:feed.results})}const assets=(await db().prepare('SELECT * FROM shorts_assets WHERE active=1').all()).results;return {job,posts:list,settings:job?JSON.parse(String(job.config)):config.shorts,assets,brand:{name:config.siteName,url:config.siteUrl}}}
if(task.kind==='upload'||task.kind==='sync'){const publication=await db().prepare('SELECT * FROM shorts_publications WHERE id=?').bind(ref).first<Row>();const output=publication?await db().prepare('SELECT * FROM shorts_outputs WHERE job_id=?').bind(publication.job_id).first<Row>():null;return {publication,output}}
return JSON.parse(String(task.payload))}
export async function failTask(task:Row,message:string,blocked=false){const retry=!blocked&&Number(task.attempts)<Number(task.max_attempts);const status=retry?'queued':'failed';const updated=await db().prepare('UPDATE worker_tasks SET status=?,run_at=?,lease_token=NULL,lease_until=NULL,error=?,updated_at=? WHERE id=? AND lease_token=?').bind(status,Date.now()+(Number(task.attempts)===1?600000:1800000),message.slice(0,1000),Date.now(),task.id,task.lease_token).run();if(!updated.meta.changes)return;await event(String(task.ref_id),blocked?'BLOCKED':status,message);
if(task.kind==='scan'){
 const source=await db().prepare('SELECT config FROM auto_sources WHERE id=?').bind(task.ref_id).first<{config:string}>();
 const identity=JSON.parse(String(task.payload)).sourceIdentity;
 if(source&&(!identity||identity===sourceIdentity(JSON.parse(source.config))))await db().prepare("UPDATE auto_sources SET last_error=?,last_run_at=?,tested_at=NULL,enabled=0,config=CASE WHEN ? THEN json_set(config,'$.enabled',json('false')) ELSE json_remove(json_set(config,'$.enabled',json('false')),'$.resumeAfterTest') END WHERE id=? AND config=?").bind(message.slice(0,1000),Date.now(),retry?1:0,task.ref_id,source.config).run();
}
if(task.kind==='render'){await db().prepare('UPDATE shorts_jobs SET status=?,error=?,retry_count=? WHERE id=?').bind(retry?'queued':'failed',message.slice(0,1000),task.attempts,task.ref_id).run();if(!retry)await db().prepare('DELETE FROM shorts_locks WHERE job_id=?').bind(task.ref_id).run()}
if(task.kind==='publish')await db().prepare('UPDATE auto_post_jobs SET status=?,attempts=?,last_error=? WHERE id=? AND post_id IS NULL').bind(retry?'queued':'failed',task.attempts,message.slice(0,1000),task.ref_id).run();
if(task.kind==='upload')await db().prepare("UPDATE shorts_publications SET status='failed',error=? WHERE id=?").bind(message.slice(0,1000),task.ref_id).run();}
