import {z} from 'zod';import {db,HttpError} from '../server';import {ops,event,taskStatement,type Row} from './server';import {shortsSchema} from './config';import {mayAutoCombine,type ShortsSourceBlock} from './shorts-policy';
export async function createShorts(owner:string,raw:unknown){const d=z.object({postIds:z.array(z.string().uuid()).min(1).max(3),force:z.boolean().default(false),config:z.record(z.string(),z.unknown()).default({})}).parse(raw),cfg=(await ops()).config;const settings=shortsSchema.parse({...cfg.shorts,...d.config});const ids=[...new Set(d.postIds)];const first=await db().prepare('SELECT body,category FROM posts WHERE id=? AND hidden=0 AND short_excluded=0').bind(ids[0]).first<{body:string;category:string}>();if(!first)throw new HttpError(404,'쇼츠 후보가 없습니다.');
if(settings.autoCombine&&ids.length<settings.maxPosts){const blocks=JSON.parse(first.body) as ShortsSourceBlock[];const estimate=blocks.reduce((n,b)=>n+(b.type==='text'?(b.text?.length||0)/10:b.type==='video'?25:3),5);if(mayAutoCombine(blocks,first.category)&&estimate<settings.minDuration){const next=await db().prepare("SELECT p.id FROM posts p WHERE p.hidden=0 AND p.short_excluded=0 AND p.id<>? AND p.category=? AND p.category<>'경제' AND NOT EXISTS(SELECT 1 FROM shorts_locks l WHERE l.post_id=p.id) ORDER BY p.created_at DESC LIMIT 1").bind(ids[0],first.category).first<{id:string}>();if(next)ids.push(next.id)}}
const id=crypto.randomUUID(),now=Date.now();const statements=[db().prepare("INSERT INTO shorts_jobs(id,status,created_by,config,plan,progress,error,retry_count,approved_at,created_at,completed_at) VALUES(?,'queued',?,?,'{}',0,'',0,NULL,?,NULL)").bind(id,owner,JSON.stringify(settings),now)];
for(const [i,postId]of ids.entries()){if(!await db().prepare('SELECT id FROM posts WHERE id=? AND hidden=0 AND short_excluded=0').bind(postId).first())throw new HttpError(404,'사용할 수 없는 글입니다.');if(!d.force&&await db().prepare("SELECT j.id FROM shorts_jobs j JOIN shorts_job_posts p ON p.job_id=j.id WHERE p.post_id=? AND j.status IN ('ready','published','scheduled') LIMIT 1").bind(postId).first())throw new HttpError(409,'이미 제작된 글입니다. 강제 재생성을 선택하세요.');if(!d.force)statements.push(db().prepare('INSERT INTO shorts_locks(post_id,job_id) VALUES(?,?)').bind(postId,id));statements.push(db().prepare('INSERT INTO shorts_job_posts(id,job_id,post_id,sequence) VALUES(?,?,?,?)').bind(crypto.randomUUID(),id,postId,i))}
statements.push(taskStatement('render',id,{},now,settings.maxRetries+1));try{await db().batch(statements)}catch(e){if(String(e).includes('UNIQUE'))throw new HttpError(409,'이미 제작 중이거나 제작한 글입니다. 강제 재생성을 선택하세요.');throw e}await event(id,'queued');return {id,postIds:ids}}
export async function queueUpload(raw:unknown){const d=z.object({id:z.string().uuid(),privacy:z.enum(['private','unlisted','scheduled','public']),scheduledAt:z.number().nullable().default(null),title:z.string().min(1).max(100),description:z.string().max(5000).default(''),tags:z.array(z.string().max(50)).max(20).default(['shorts','유머']),confirmPublic:z.boolean().default(false)}).parse(raw);if(d.privacy==='public'&&!d.confirmPublic)throw new HttpError(400,'즉시 공개를 명시적으로 확인해 주세요.');if(d.privacy==='scheduled'&&(!d.scheduledAt||d.scheduledAt<Date.now()+600000))throw new HttpError(400,'예약은 10분 이후로 설정해 주세요.');const j=await db().prepare("SELECT j.id,j.approved_at FROM shorts_jobs j JOIN shorts_outputs o ON o.job_id=j.id WHERE j.id=? AND j.status='ready' AND o.qc_status='passed'").bind(d.id).first<Row>();if(!j?.approved_at)throw new HttpError(409,'QC 통과 후 관리자 승인이 필요합니다.');const existing=await db().prepare('SELECT * FROM shorts_publications WHERE job_id=?').bind(d.id).first<Row>();if(existing&&existing.status!=='failed')throw new HttpError(409,'이미 업로드가 요청됐습니다.');const id=String(existing?.id||crypto.randomUUID());await db().batch([db().prepare("INSERT INTO shorts_publications(id,job_id,external_id,privacy,status,scheduled_at,published_at,metadata,upload_session,last_synced_at,created_at,error) VALUES(?,?,'',?,'upload_queued',?,NULL,?,'',NULL,?,'') ON CONFLICT(job_id) DO UPDATE SET status='upload_queued',error='',privacy=excluded.privacy,scheduled_at=excluded.scheduled_at,metadata=excluded.metadata").bind(id,d.id,d.privacy,d.scheduledAt,JSON.stringify({title:d.title,description:d.description,tags:d.tags}),Date.now()),taskStatement('upload',id,{},Date.now(),1)]);await event(d.id,'upload_queued');return {id}}

export function autoTitle(raw:string,prefix:string,max:number){const clean=raw.replace(/\[[^\]]{0,20}\]|\([^)]{0,20}\)/g,' ').replace(/[​\s]+/g,' ').replace(/[ㅋㅎㅠㅜ]{3,}/g,m=>m.slice(0,2)).trim()||'오늘의 유머';const chars=Array.from(clean);const short=chars.length>max?chars.slice(0,max).join('').replace(/\s+\S*$/,'')+'…':clean;return (prefix+short).slice(0,100)}
export async function autoPublish(jobId:string){const cfg=(await ops()).config.shorts,job=await db().prepare('SELECT config FROM shorts_jobs WHERE id=?').bind(jobId).first<{config:string}>(),s=shortsSchema.parse({...cfg,...JSON.parse(job?.config||'{}')});if(!s.autoUpload)return null;const posts=await db().prepare('SELECT p.title,p.category FROM posts p JOIN shorts_job_posts j ON j.post_id=p.id WHERE j.job_id=? ORDER BY j.sequence').bind(jobId).all<{title:string;category:string}>();const first=posts.results[0];if(!first)return null;const approved=await db().prepare("UPDATE shorts_jobs SET approved_at=? WHERE id=? AND status='ready' AND approved_at IS NULL AND EXISTS(SELECT 1 FROM shorts_outputs WHERE job_id=? AND qc_status='passed')").bind(Date.now(),jobId,jobId).run();if(!approved.meta.changes)return null;const tags=[...new Set([...s.tags,first.category])].slice(0,15),title=autoTitle(first.title,s.titlePrefix,s.titleMaxLength);const site=(await ops()).config.siteUrl;return queueUpload({id:jobId,privacy:s.autoUploadPrivacy,scheduledAt:null,title,description:[posts.results.map(p=>p.title).join(' / '),site?'더 많은 유머: '+site:'','#Shorts '+tags.map(t=>'#'+t.replace(/\s/g,'')).join(' ')].filter(Boolean).join('\n\n'),tags,confirmPublic:s.autoUploadPrivacy==='public'})}

type Candidate={id:string;title:string;body:string;category:string;views:number;likes:number;comments:number};
export function estimateSeconds(posts:{title:string;body:string}[]){let t=1.1+3;for(const [i,p] of posts.entries()){const blocks=JSON.parse(p.body) as ShortsSourceBlock[];t+=(i?.6:0)+3+Math.max(3,Array.from(p.title).length/10);for(const b of blocks)t+=b.type==='text'?Math.max(2,Array.from(b.text||'').length/10+1):b.type==='video'?10:b.type==='youtube'?0:3}return t}
export async function createFullPackage(owner:string,raw:unknown){const d=z.object({minForty:z.boolean().default(false)}).parse(raw),cfg=(await ops()).config.shorts,rows=(await db().prepare("SELECT p.id,p.title,p.body,p.category,p.views,(SELECT COUNT(*) FROM likes WHERE post_id=p.id) likes,(SELECT COUNT(*) FROM comments WHERE post_id=p.id) comments FROM posts p WHERE p.hidden=0 AND p.short_excluded=0 AND p.category<>'경제' AND NOT EXISTS(SELECT 1 FROM shorts_locks l WHERE l.post_id=p.id) AND NOT EXISTS(SELECT 1 FROM shorts_job_posts jp JOIN shorts_jobs j ON j.id=jp.job_id WHERE jp.post_id=p.id AND j.status IN ('ready','published','scheduled')) ORDER BY p.created_at DESC LIMIT 200").all<Candidate>()).results;const score=(r:Candidate)=>r.likes*5+r.comments*3+r.views*.01,ranked=rows.sort((a,b)=>score(b)-score(a)),max=cfg.maxDuration>=60?60:cfg.maxDuration;
const fits=ranked.filter(r=>estimateSeconds([r])<=max-2);const chosen:Candidate[]=[];if(d.minForty){for(const r of fits){chosen.push(r);if(estimateSeconds(chosen)>=42||chosen.length===3)break}if(estimateSeconds(chosen)>max-2)chosen.pop()}else if(fits[0])chosen.push(fits[0]);if(!chosen.length)throw new HttpError(404,'풀패키지로 만들 수 있는 새 글이 없습니다. (경제글·제외글·이미 제작한 글은 건너뜁니다)');
const introStyle=(['classic','impact','motion'] as const)[Math.floor(Math.random()*3)];const config:Record<string,unknown>={introStyle,intro:true,outro:true,bgmEnabled:true,bgmRandom:true,autoUpload:true,autoCombine:false,maxPosts:3,...(d.minForty?{minDuration:40,targetDuration:42,maxDuration:max}:{})};const r=await createShorts(owner,{postIds:chosen.map(c=>c.id),force:false,config});return {...r,introStyle,titles:chosen.map(c=>c.title)}}
