import React,{useEffect,useState} from 'react';
import {registerRoot,Composition,AbsoluteFill,Sequence,Img,OffthreadVideo,Audio,useCurrentFrame,staticFile,delayRender,continueRender,cancelRender} from 'remotion';
import {Gif} from '@remotion/gif';
const ink='#25243b',purple='#6154db';
const titleStyle=text=>({fontSize:Math.min(64,Math.max(25,Math.floor(610/Math.sqrt(Math.max(1,Array.from(text).length))))),lineHeight:1.4,fontWeight:800,overflowWrap:'anywhere',whiteSpace:'pre-wrap'});
function Scene({scene,settings}){
 const frame=useCurrentFrame(),p=scene.payload;
 if(scene.type==='video_play')return <OffthreadVideo src={p.src} startFrom={p.startFrame||0} volume={settings.originalVolume} style={{width:'100%',height:'100%',objectFit:'contain'}}/>;
 if(scene.type==='gif_play')return <Gif src={p.src} width={840} height={1170} fit="contain"/>;
 if(scene.type==='image_hold')return <Img src={p.src} style={{width:'100%',height:'100%',objectFit:'contain'}}/>;
 if(scene.type==='feed_open')return <div style={{padding:30,width:'100%'}}><div style={{fontSize:32,color:purple,borderBottom:'2px solid #eeedf7',paddingBottom:28}}>스르륵　 ·　 인기글</div><div style={{position:'relative',marginTop:45,padding:30,borderRadius:22,background:frame>=24?'#eeebff':'#fafaff',border:'3px solid '+(frame>=24?purple:'#e9e7f3'),transform:frame>=30&&frame<40?'scale(.98)':'none'}}><div style={{fontSize:26,color:purple,marginBottom:20}}>오늘 같이 볼 글</div><div style={titleStyle(p.text)}>{p.text}</div>{p.src&&<Img src={p.src} style={{marginTop:30,width:'100%',height:390,objectFit:'contain',borderRadius:16}}/>}<div style={{fontSize:28,color:purple,marginTop:32}}>글 보러 가기 →</div>{frame>=18&&<div style={{position:'absolute',right:38,bottom:20,width:70,height:70,borderRadius:'50%',border:'5px solid '+purple,background:'#6154db22',transform:`scale(${frame<30?1:1+(frame-30)/35})`,opacity:frame<30?1:Math.max(0,1-(frame-30)/25)}}/>}</div></div>;
 if(scene.type==='post_title')return <div style={{padding:28,width:'100%',display:'flex',flexDirection:'column',gap:30}}><div style={{fontSize:26,color:purple}}>하루 한 번, 같이 웃어요</div><div style={{...titleStyle(p.text),maxHeight:570}}>{p.text}</div>{p.src&&<Img src={p.src} style={{width:'100%',height:510,objectFit:'contain',borderRadius:18}}/>}</div>;
 return <div style={{padding:26,width:'100%',fontSize:40,lineHeight:'70px',whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontWeight:500,color:ink}}>{scene.type==='comments'&&<div style={{fontSize:28,color:purple,marginBottom:24}}>댓글 같이 보기</div>}{p.text}{p.reaction&&settings.effects!=='off'&&<div style={{marginTop:25,color:purple,fontSize:55,fontWeight:800}}>{p.reaction}</div>}{scene.type==='outro'&&<div style={{marginTop:90,fontSize:48,color:purple,fontWeight:800}}>www.ssrrr.net</div>}</div>;
}
function Video({plan}){
 const [fontHandle]=useState(()=>delayRender('Load bundled Korean font'));
 useEffect(()=>{const font=new FontFace('ShortsKorean',`url("${staticFile('fonts/NotoSansKR.ttf')}")`,{weight:'100 900'});font.load().then(f=>{document.fonts.add(f);continueRender(fontHandle)}).catch(cancelRender)},[fontHandle]);
 const frame=useCurrentFrame(),s=plan.settings,active=plan.scenes.find(x=>frame>=x.from&&frame<x.from+x.frames);
 const original=active?.type==='video_play'&&active.payload.hasAudio,bgmGain=original?(s.audioPolicy==='off'?0:s.audioPolicy==='duck'?s.bgmVolume*.2:s.bgmVolume):s.bgmVolume;
 return <AbsoluteFill style={{background:'#f0eefb',fontFamily:'ShortsKorean, sans-serif',color:ink}}><style>{'*{box-sizing:border-box}'}</style>{plan.background&&<Img src={plan.background} style={{position:'absolute',width:'100%',height:'100%',objectFit:'cover'}}/>}<div style={{position:'absolute',top:100,left:65,right:170,fontSize:43,fontWeight:800,color:purple,display:'flex',gap:16,alignItems:'center'}}>{plan.logo&&<Img src={plan.logo} style={{width:60,height:60,objectFit:'contain'}}/>}오늘의 스르륵 인기글</div><div style={{position:'absolute',top:176,left:70,fontSize:25,color:'#716b91'}}>하루 1 유머 · 스르륵</div><div style={{position:'absolute',left:55,right:165,top:260,height:1230,overflow:'hidden',borderRadius:28,background:'#fffffff5',padding:20}}>{plan.scenes.map((scene,i)=><Sequence key={i} from={scene.from} durationInFrames={scene.frames}><Scene scene={scene} settings={s}/></Sequence>)}</div>{(s.watermark||s.cta)&&<div style={{position:'absolute',left:70,bottom:300,fontSize:43,fontWeight:800,color:purple}}>www.ssrrr.net</div>}{s.cta&&<div style={{position:'absolute',left:70,bottom:245,fontSize:29,color:ink}}>더 많은 유머와 댓글은 스르륵에서</div>}{s.effects!=='off'&&plan.sfx&&plan.scenes.filter(x=>['feed_open','transition','outro'].includes(x.type)).map((x,i)=><Sequence key={'sfx'+i} from={x.from} durationInFrames={Math.min(15,x.frames)}><Audio src={plan.sfx} volume={s.effects==='normal'?.15:.07}/></Sequence>)}{s.bgmEnabled&&plan.bgm&&<Audio src={plan.bgm} loop volume={()=>bgmGain}/>}</AbsoluteFill>;
}
const Root=()=> <Composition id="SecretAgitShort" component={Video} width={1080} height={1920} fps={30} durationInFrames={60} defaultProps={{plan:{scenes:[],settings:{},brand:{name:'스르륵'}}}} calculateMetadata={({props})=>({durationInFrames:Math.max(1,props.plan.durationFrames)})}/>;
registerRoot(Root);
