import React,{useEffect,useState} from 'react';
import {registerRoot,Composition,AbsoluteFill,Sequence,Img,OffthreadVideo,Audio,useCurrentFrame,staticFile,delayRender,continueRender,cancelRender} from 'remotion';
import {Gif} from '@remotion/gif';
const ink='#25243b',purple='#6154db';
const titleStyle=text=>({fontSize:Math.min(64,Math.max(25,Math.floor(610/Math.sqrt(Math.max(1,Array.from(text).length))))),lineHeight:1.4,fontWeight:800,overflowWrap:'anywhere',whiteSpace:'pre-wrap'});
const mediaTitleStyle={position:'absolute',zIndex:4,top:28,left:28,right:28,padding:'20px 24px',borderRadius:20,background:'#171424d9',color:'#fff',fontSize:34,lineHeight:1.35,fontWeight:800,textShadow:'0 2px 8px #0008'};
function MediaStage({scene,settings}){const p=scene.payload,video=scene.type==='video_play',gif=scene.type==='gif_play';return <div style={{position:'relative',width:'100%',height:'100%',overflow:'hidden',background:'#171424'}}>{!video&&<Img src={p.src} style={{position:'absolute',inset:-45,width:'calc(100% + 90px)',height:'calc(100% + 90px)',objectFit:'cover',filter:'blur(34px) saturate(.85) brightness(.52)',opacity:.92}}/>}<div style={mediaTitleStyle}>{p.title||'오늘의 스르륵'}</div><div style={{position:'absolute',inset:'118px 0 70px',display:'grid',placeItems:'center'}}>{video?<OffthreadVideo src={p.src} startFrom={p.startFrame||0} volume={settings.originalVolume} style={{width:'100%',height:'100%',objectFit:'contain'}}/>:gif?<Gif src={p.src} width={1024} height={1260} fit="contain"/>:<Img src={p.src} style={{width:'100%',height:'100%',objectFit:'contain',filter:'drop-shadow(0 14px 28px #0008)'}}/>}</div><div style={{position:'absolute',zIndex:4,left:28,bottom:22,padding:'10px 17px',borderRadius:999,background:'#171424bf',color:'#fff',fontSize:24,fontWeight:700}}>스르륵 · {p.mediaIndex||1}</div></div>}
function Scene({scene,settings}){
 const frame=useCurrentFrame(),p=scene.payload;
 if(['video_play','gif_play','image_hold'].includes(scene.type))return <MediaStage scene={scene} settings={settings}/>;
 if(scene.type==='feed_open')return <div style={{position:'relative',width:'100%',height:'100%',overflow:'hidden',background:'linear-gradient(145deg,#302a72,#7266ee)'}}>{p.src&&<Img src={p.src} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',filter:'blur(26px) brightness(.42)',transform:'scale(1.12)'}}/>}<div style={{position:'absolute',inset:0,background:'linear-gradient(180deg,#24204355,#242043ee)'}}/><div style={{position:'absolute',left:48,right:48,bottom:110,color:'#fff'}}><div style={{fontSize:30,fontWeight:700,marginBottom:24,color:'#dcd8ff'}}>오늘의 스르륵 인기글</div><div style={titleStyle(p.text)}>{p.text}</div><div style={{marginTop:35,fontSize:30,fontWeight:700}}>커뮤니티에서 글을 누르면 시작 ↗</div></div></div>;
 if(scene.type==='post_title')return <div style={{position:'relative',width:'100%',height:'100%',overflow:'hidden',background:'#fff'}}>{p.src&&<Img src={p.src} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',filter:'blur(32px) brightness(.42)',transform:'scale(1.14)'}}/>}<div style={{position:'absolute',inset:0,background:'linear-gradient(180deg,#28233aaa,#28233af2)'}}/><div style={{position:'absolute',left:48,right:48,top:80,color:'#fff'}}><div style={{fontSize:27,color:'#d9d5ff',marginBottom:24}}>하루 한 번, 같이 웃어요</div><div style={{...titleStyle(p.text),fontSize:Math.min(70,titleStyle(p.text).fontSize+8)}}>{p.text}</div></div><div style={{position:'absolute',left:48,bottom:70,color:'#fff',fontSize:27}}>잠시 후 원본 이미지를 크게 보여드려요</div></div>;
 if(scene.type==='outro')return <div style={{width:'100%',height:'100%',display:'grid',placeContent:'center',textAlign:'center',padding:50,background:'linear-gradient(145deg,#302a72,#7569f1)',color:'#fff'}}><div style={{fontSize:40,lineHeight:1.5,fontWeight:700,whiteSpace:'pre-wrap'}}>{p.text}</div><div style={{marginTop:54,fontSize:58,fontWeight:900}}>www.ssrrr.net</div></div>;
 return <div style={{width:'100%',height:'100%',padding:'58px 52px',fontSize:44,lineHeight:'72px',whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontWeight:600,color:ink,background:'#fffffff2'}}>{scene.type==='comments'&&<div style={{fontSize:29,color:purple,marginBottom:28,fontWeight:800}}>댓글 같이 보기</div>}{p.text}{p.reaction&&settings.effects!=='off'&&<div style={{marginTop:28,color:purple,fontSize:58,fontWeight:900}}>{p.reaction}</div>}</div>;
}
function Video({plan}){
 const [fontHandle]=useState(()=>delayRender('Load bundled Korean font'));
 useEffect(()=>{const font=new FontFace('ShortsKorean',`url("${staticFile('fonts/NotoSansKR.ttf')}")`,{weight:'100 900'});font.load().then(f=>{document.fonts.add(f);continueRender(fontHandle)}).catch(cancelRender)},[fontHandle]);
 const frame=useCurrentFrame(),s=plan.settings,active=plan.scenes.find(x=>frame>=x.from&&frame<x.from+x.frames);
 const original=active?.type==='video_play'&&active.payload.hasAudio,bgmGain=original?(s.audioPolicy==='off'?0:s.audioPolicy==='duck'?s.bgmVolume*.2:s.bgmVolume):s.bgmVolume;
 return <AbsoluteFill style={{background:'linear-gradient(180deg,#eeecff,#dcd8fb)',fontFamily:'ShortsKorean, sans-serif',color:ink}}><style>{'*{box-sizing:border-box}'}</style>{plan.background&&<Img src={plan.background} style={{position:'absolute',width:'100%',height:'100%',objectFit:'cover'}}/>}<div style={{position:'absolute',top:48,left:32,right:32,height:86,borderRadius:26,background:'#ffffffeb',boxShadow:'0 12px 34px #36305b24',padding:'0 30px',fontSize:38,fontWeight:900,color:purple,display:'flex',gap:15,alignItems:'center',zIndex:10}}>{plan.logo&&<Img src={plan.logo} style={{width:54,height:54,objectFit:'contain'}}/>}오늘의 스르륵 <span style={{marginLeft:'auto',fontSize:24,color:'#716b91'}}>인기글</span></div><div style={{position:'absolute',left:28,right:28,top:154,bottom:190,overflow:'hidden',borderRadius:34,background:'#fff',boxShadow:'0 18px 55px #302b5c38'}}>{plan.scenes.map((scene,i)=><Sequence key={i} from={scene.from} durationInFrames={scene.frames}><Scene scene={scene} settings={s}/></Sequence>)}</div>{(s.watermark||s.cta)&&<div style={{position:'absolute',left:42,bottom:102,fontSize:42,fontWeight:900,color:purple}}>www.ssrrr.net</div>}{s.cta&&<div style={{position:'absolute',right:42,bottom:108,fontSize:25,fontWeight:700,color:ink}}>더 많은 유머는 스르륵에서</div>}{s.effects!=='off'&&plan.sfx&&plan.scenes.filter(x=>['feed_open','transition','outro'].includes(x.type)).map((x,i)=><Sequence key={'sfx'+i} from={x.from} durationInFrames={Math.min(15,x.frames)}><Audio src={plan.sfx} volume={s.effects==='normal'?.15:.07}/></Sequence>)}{s.bgmEnabled&&plan.bgm&&<Audio src={plan.bgm} loop volume={()=>bgmGain}/>}</AbsoluteFill>;
}
const Root=()=> <Composition id="SecretAgitShort" component={Video} width={1080} height={1920} fps={30} durationInFrames={60} defaultProps={{plan:{scenes:[],settings:{},brand:{name:'스르륵'}}}} calculateMetadata={({props})=>({durationInFrames:Math.max(1,props.plan.durationFrames)})}/>;
registerRoot(Root);
