import React,{useEffect,useState} from 'react';
import {registerRoot,Composition,AbsoluteFill,Sequence,Img,OffthreadVideo,Audio,useCurrentFrame,staticFile,delayRender,continueRender,cancelRender} from 'remotion';
import {Gif} from '@remotion/gif';
import {easeScroll} from '../planner.mjs';

const ink='#26283a',purple='#514be8',muted='#8d91a4',line='#e7e8ef',page='#f6f7fb';
const titleSize=text=>Math.min(58,Math.max(34,Math.floor(650/Math.sqrt(Math.max(1,Array.from(text||'').length)))));

function SiteHeader(){return <><div style={{height:44,display:'grid',placeItems:'center',background:'#f0efff',color:'#6963b7',fontSize:20}}>안녕하세요 대한민국 no.1 유머사이트 스르륵입니다.</div><div style={{height:104,display:'flex',alignItems:'center',gap:24,padding:'0 38px',background:'#fff',borderBottom:'1px solid '+line}}><Img src={staticFile('images/ssrrr-logo-3.png')} style={{width:220,height:58,objectFit:'contain',objectPosition:'left center'}}/><div style={{marginLeft:'auto',width:330,padding:'17px 22px',borderRadius:13,background:'#f5f6fa',color:'#999dac',fontSize:21}}>재미있는 이야기 찾기</div><b style={{fontSize:21}}>로그인</b></div></>}

function BoardNav({category='유머'}){const items=['전체','유머','짤','영상','SNS','이슈','자유게시판'];return <div style={{height:82,display:'flex',gap:9,alignItems:'center',padding:'0 28px',background:'#fff',borderBottom:'1px solid '+line,overflow:'hidden'}}>{items.map(item=><div key={item} style={{flexShrink:0,padding:'12px 18px',borderRadius:10,background:item===category?'#eae9ff':'transparent',color:item===category?'#4b45d3':'#65697f',fontSize:22,fontWeight:750}}>{item}</div>)}</div>}

function Footer(){return <div style={{position:'absolute',left:0,right:0,bottom:0,height:96,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 38px',background:'#fff',borderTop:'1px solid '+line,zIndex:20}}><b style={{fontSize:34,color:purple}}>www.ssrrr.net</b><span style={{fontSize:21,color:'#666b80'}}>오늘의 웃음을 모으는 곳</span></div>}

function Chrome({children,category}){return <AbsoluteFill style={{background:page,color:ink}}><SiteHeader/><BoardNav category={category}/>{children}<Footer/></AbsoluteFill>}

function FeedRow({row,target,src,active}){return <div style={{position:'relative',padding:'24px 26px',borderBottom:'1px solid #f0f0f6',background:active?'#eeedff':'#fff',transform:active?'scale(.985)':'none',boxShadow:active?'inset 6px 0 0 '+purple:'none'}}><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'center'}}><div style={{minWidth:0,flex:1}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{padding:'5px 10px',borderRadius:6,background:'#eeedff',color:'#655fe0',fontSize:17,fontWeight:800}}>{row.category||'유머'}</span><span style={{fontSize:17,color:muted}}>{row.nickname||'꿀잼픽'} · 오늘</span></div><div style={{fontSize:29,lineHeight:1.45,fontWeight:800,margin:'14px 0',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{row.title}</div><div style={{fontSize:18,color:muted}}>♡ {row.likes||0}　💬 {row.comments||0}　조회 {row.views||0}</div></div>{target&&src&&<Img src={src} style={{width:154,height:122,objectFit:'cover',borderRadius:12,background:'#f1f2f7'}}/>}</div>{active&&<div style={{position:'absolute',right:54,bottom:32,width:68,height:68,borderRadius:'50%',border:'5px solid '+purple,background:'#514be82a'}}/>}</div>}

function FeedScene({scene}){const frame=useCurrentFrame(),p=scene.payload,supplied=(p.feed||[]).filter(row=>row&&row.title),target=supplied.find(row=>String(row.id)===String(p.targetId))||{id:p.targetId,title:p.title,category:p.category,nickname:p.nickname,views:p.views},others=supplied.filter(row=>String(row.id)!==String(p.targetId)),rows=[others[0]||{title:'오늘 다들 빵 터진 이야기 모음',category:p.category},target,others[1]||{title:'방금 올라온 따끈한 유머글',category:p.category}],active=frame>=Math.max(18,scene.frames*.52);return <Chrome category={p.category}><div style={{position:'absolute',top:248,left:28,right:28,bottom:116,overflow:'hidden'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',margin:'18px 8px 24px'}}><div><h1 style={{margin:0,fontSize:42}}>{p.category||'유머'}</h1><p style={{margin:'9px 0 0',fontSize:21,color:muted}}>오늘 같이 웃을 이야기를 골라보세요.</p></div><div style={{padding:'13px 20px',borderRadius:10,background:purple,color:'#fff',fontSize:20,fontWeight:800}}>글쓰기</div></div><div style={{display:'flex',gap:18,alignItems:'center',padding:'18px 24px',background:'#edecff',border:'1px solid #e0ddff',borderRadius:16,marginBottom:22}}><span style={{fontSize:42}}>🐤</span><div><b style={{fontSize:24,color:'#4f49a8'}}>새로 모이는 우리들의 아지트</b><p style={{margin:'5px 0 0',fontSize:18,color:'#777197'}}>유머부터 소소한 일상까지, 스르륵 둘러보세요.</p></div></div><div style={{border:'1px solid '+line,borderRadius:16,overflow:'hidden',background:'#fff'}}><div style={{height:64,display:'flex',alignItems:'center',gap:24,padding:'0 24px',borderBottom:'1px solid '+line,fontSize:20,fontWeight:800}}><span>최신순</span><span style={{color:purple}}>🔥 유머 인기글</span></div><div style={{padding:'15px 24px',background:'#fafaff',borderBottom:'1px solid '+line,color:'#777b90',fontSize:18}}><b style={{color:purple}}>안내</b>　사진 · 영상 첨부를 지원해요.</div>{rows.map((row,i)=><FeedRow key={String(row.id||i)} row={row} target={row===target} src={p.src} active={row===target&&active}/>)}</div>{active&&<div style={{textAlign:'center',marginTop:24,color:purple,fontSize:24,fontWeight:850}}>선택한 글로 들어가는 중…</div>}</div></Chrome>}

function ArticleHead({p,compact=false}){return <><div style={{color:muted,fontSize:21,marginBottom:18}}>← 이야기 목록</div><div style={{display:'inline-block',padding:'7px 12px',borderRadius:7,background:'#eeedff',color:'#655fe0',fontSize:18,fontWeight:800}}>{p.category||'유머'}</div><h1 style={{fontSize:compact?38:titleSize(p.title),lineHeight:1.42,letterSpacing:-1.1,margin:'18px 0 14px'}}>{p.title||'오늘의 스르륵'}</h1><div style={{display:'flex',gap:18,color:muted,fontSize:19,paddingBottom:compact?19:28,borderBottom:'1px solid '+line}}><span>{p.nickname||'꿀잼픽'}</span><span>오늘</span><span>조회 {p.views||0}</span></div></>}

function TitleScene({scene}){const p=scene.payload;return <Chrome category={p.category}><div style={{position:'absolute',top:274,left:28,right:28,bottom:124,padding:'32px 34px',border:'1px solid #e4e6ef',borderRadius:16,background:'#fff',overflow:'hidden'}}><ArticleHead p={p}/>{p.src&&<Img src={p.src} style={{display:'block',width:'100%',height:900,marginTop:34,objectFit:'contain',objectPosition:'top center',borderRadius:10,background:'#f1f2f7'}}/>}</div></Chrome>}

function MediaScene({scene,settings}){const p=scene.payload,video=scene.type==='video_play',gif=scene.type==='gif_play';return <Chrome category={p.category}><div style={{position:'absolute',top:262,left:22,right:22,bottom:112,padding:'24px 26px 30px',border:'1px solid #e4e6ef',borderRadius:16,background:'#fff',overflow:'hidden'}}><ArticleHead p={p} compact/><div style={{height:1010,marginTop:24,display:'grid',placeItems:'center',overflow:'hidden',borderRadius:10,background:'#f0f1f6'}}>{video?<OffthreadVideo src={p.src} startFrom={p.startFrame||0} volume={settings.originalVolume} style={{width:'100%',height:'100%',objectFit:'contain'}}/>:gif?<Gif src={p.src} width={984} height={1010} fit="contain"/>:<Img src={p.src} style={{width:'100%',height:'100%',objectFit:'contain'}}/>}</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:22,color:muted,fontSize:19}}><span>첨부 사진 {p.mediaIndex||1}</span><span>♡ 추천　💬 댓글</span></div></div></Chrome>}

function TextScene({scene,settings}){const frame=useCurrentFrame(),p=scene.payload,text=p.text||'',lines=Math.max(1,text.split('\n').length+Math.ceil(Array.from(text).length/20)),distance=Math.max(0,lines*70-780),offset=scene.type==='post_body_scroll'?easeScroll(frame+(p.startFrame||0),p.totalFrames||scene.frames,distance):0;return <Chrome category={p.category}><div style={{position:'absolute',top:262,left:22,right:22,bottom:112,padding:'24px 30px',border:'1px solid #e4e6ef',borderRadius:16,background:'#fff',overflow:'hidden'}}><ArticleHead p={p} compact/><div style={{marginTop:26,paddingTop:scene.type==='comments'?24:0,borderTop:scene.type==='comments'?'1px solid '+line:'none'}}>{scene.type==='comments'&&<div style={{fontSize:27,fontWeight:850,marginBottom:22}}>댓글 <span style={{color:purple}}>같이 보기</span></div>}<div style={{fontSize:39,lineHeight:'70px',fontWeight:scene.type==='comments'?500:600,whiteSpace:'pre-wrap',overflowWrap:'anywhere',transform:`translateY(${offset}px)`}}>{text}</div>{p.reaction&&settings.effects!=='off'&&<div style={{marginTop:28,color:purple,fontSize:58,fontWeight:900}}>{p.reaction}</div>}</div></div></Chrome>}

function OtherScene({scene}){const p=scene.payload;if(scene.type==='outro')return <Chrome category="유머"><div style={{position:'absolute',top:300,left:58,right:58,bottom:180,display:'grid',placeContent:'center',textAlign:'center',borderRadius:28,background:'linear-gradient(145deg,#302a72,#7569f1)',color:'#fff',padding:55}}><div style={{fontSize:42,lineHeight:1.55,fontWeight:800,whiteSpace:'pre-wrap'}}>{p.text}</div><div style={{marginTop:58,fontSize:64,fontWeight:950}}>www.ssrrr.net</div><div style={{marginTop:24,fontSize:26}}>직접 들어와서 다음 글도 스르륵</div></div></Chrome>;return <Chrome category="유머"><div style={{position:'absolute',inset:'280px 40px 150px',display:'grid',placeContent:'center',textAlign:'center',fontSize:44,fontWeight:850,color:purple}}>다음 이야기로 이동 중…</div></Chrome>}

function Scene({scene,settings}){if(scene.type==='feed_open')return <FeedScene scene={scene}/>;if(scene.type==='post_title')return <TitleScene scene={scene}/>;if(['image_hold','gif_play','video_play'].includes(scene.type))return <MediaScene scene={scene} settings={settings}/>;if(['post_body_scroll','comments'].includes(scene.type))return <TextScene scene={scene} settings={settings}/>;return <OtherScene scene={scene}/>}

function Video({plan}){const [fontHandle]=useState(()=>delayRender('Load bundled Korean font'));useEffect(()=>{const font=new FontFace('ShortsKorean',`url("${staticFile('fonts/NotoSansKR.ttf')}")`,{weight:'100 900'});font.load().then(loaded=>{document.fonts.add(loaded);continueRender(fontHandle)}).catch(cancelRender)},[fontHandle]);const frame=useCurrentFrame(),settings=plan.settings,active=plan.scenes.find(scene=>frame>=scene.from&&frame<scene.from+scene.frames),original=active?.type==='video_play'&&active.payload.hasAudio,bgmGain=original?(settings.audioPolicy==='off'?0:settings.audioPolicy==='duck'?settings.bgmVolume*.2:settings.bgmVolume):settings.bgmVolume;return <AbsoluteFill style={{background:page,fontFamily:'ShortsKorean, sans-serif',color:ink}}><style>{'*{box-sizing:border-box}'}</style>{plan.scenes.map((scene,index)=><Sequence key={index} from={scene.from} durationInFrames={scene.frames}><Scene scene={scene} settings={settings}/></Sequence>)}{settings.effects!=='off'&&plan.sfx&&plan.scenes.filter(scene=>['feed_open','transition','outro'].includes(scene.type)).map((scene,index)=><Sequence key={'sfx'+index} from={scene.from} durationInFrames={Math.min(15,scene.frames)}><Audio src={plan.sfx} volume={settings.effects==='normal'?.15:.07}/></Sequence>)}{settings.bgmEnabled&&plan.bgm&&<Audio src={plan.bgm} loop volume={()=>bgmGain}/>}</AbsoluteFill>}

const Root=()=> <Composition id="SecretAgitShort" component={Video} width={1080} height={1920} fps={30} durationInFrames={60} defaultProps={{plan:{scenes:[],settings:{},brand:{name:'스르륵'}}}} calculateMetadata={({props})=>({durationInFrames:Math.max(1,props.plan.durationFrames)})}/>;
registerRoot(Root);
