import {load} from 'cheerio';
export async function accessToken(service,fetcher=fetch){const prefix=service.toUpperCase();const client_id=process.env[prefix+'_CLIENT_ID'],client_secret=process.env[prefix+'_CLIENT_SECRET'],refresh_token=process.env[prefix+'_REFRESH_TOKEN'];if(!client_id||!client_secret||!refresh_token)throw Error('WAITING_FOR_USER: '+prefix+' OAuth credential');const r=await fetcher('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id,client_secret,refresh_token,grant_type:'refresh_token'})});const d=await r.json();if(!r.ok||!d.access_token)throw Error(prefix+'_OAUTH_FAILED: '+(d.error||r.status));return d.access_token}
async function google(url,token,options={},fetcher=fetch){const r=await fetcher(url,{...options,headers:{Authorization:'Bearer '+token,...options.headers}});if(!r.ok)throw Error('GOOGLE_API_'+r.status);return r.json()}
export function mailBody(payload){const visit=(p,type)=>{if(p.mimeType===type&&p.body?.data)return Buffer.from(p.body.data,'base64url').toString('utf8');for(const part of p.parts||[]){const v=visit(part,type);if(v)return v}return ''};const plain=visit(payload,'text/plain');if(plain)return plain;const $=load(visit(payload,'text/html'));$('script,style,blockquote,.gmail_quote,.gmail_signature').remove();$('br').replaceWith('\n');$('p,div,li').append('\n');return $.text()}
function mailPart(payload,type){if(payload.mimeType===type&&payload.body?.data)return Buffer.from(payload.body.data,'base64url').toString('utf8');for(const part of payload.parts||[]){const value=mailPart(part,type);if(value)return value}return ''}
function safeChatGptUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='chatgpt.com'?url.href:''}catch{return ''}}
export function taskMessageLink(payload){const html=mailPart(payload,'text/html');if(html){const $=load(html);for(const anchor of $('a').toArray()){const label=$(anchor).text().replace(/\s+/g,' ').trim();if(!/^(?:view|open|read)(?: the)? message$|^메시지 (?:보기|열기)$/i.test(label))continue;const direct=safeChatGptUrl($(anchor).attr('href')||'');if(direct)return direct}}const plain=mailPart(payload,'text/plain');for(const match of plain.matchAll(/https:\/\/[^\s<>"']+/g)){const direct=safeChatGptUrl(match[0].replace(/[),.;]+$/,''));if(direct)return direct}return ''}

const MAIL_LABELS={DONE:'AUTO_POST_DONE',ERROR:'AUTO_POST_ERROR',REVIEW:'AUTO_POST_REVIEW'};
async function gmailContext(config,fetcher){if(Object.values(MAIL_LABELS).includes(config.gmailLabel))throw Error('INVALID_SOURCE_LABEL: use AUTO_POST');if(!config.gmailMailbox)throw Error('WAITING_FOR_USER: 전용 Gmail 주소');const token=await accessToken('gmail',fetcher),base='https://gmail.googleapis.com/gmail/v1/users/me';const profile=await google(base+'/profile',token,{},fetcher);if(profile.emailAddress.toLowerCase()!==config.gmailMailbox.toLowerCase())throw Error('BLOCKED: DEDICATED_MAILBOX_MISMATCH');const labels=(await google(base+'/labels',token,{},fetcher)).labels||[],source=labels.find(x=>x.name===config.gmailLabel);if(!source)throw Error('BLOCKED: AUTO_POST_LABEL_MISSING');const targets={};for(const [outcome,name] of Object.entries(MAIL_LABELS)){let label=labels.find(x=>x.name===name);if(!label){label=await google(base+'/labels',token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,labelListVisibility:'labelShow',messageListVisibility:'show'})},fetcher)}if(!label?.id)throw Error('GMAIL_LABEL_CREATE_FAILED');targets[outcome]=label.id}return {token,base,source,targets,mailbox:profile.emailAddress}}
async function moveMail(ctx,id,outcome,fetcher){await google(ctx.base+'/messages/'+encodeURIComponent(id)+'/modify',ctx.token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({addLabelIds:[ctx.targets[outcome]],removeLabelIds:[ctx.source.id,...Object.values(ctx.targets).filter(x=>x!==ctx.targets[outcome])]})},fetcher)}
export async function relabelGmail(config,providerId,outcome,fetcher=fetch){if(!MAIL_LABELS[outcome])throw Error('INVALID_MAIL_OUTCOME');const ctx=await gmailContext(config,fetcher);await moveMail(ctx,providerId,outcome,fetcher);return {label:MAIL_LABELS[outcome]}}
export async function pollGmail(config,onMessage,fetcher=fetch){if(!config.gmailEnabled||!config.gmailMailbox||!config.gmailSenders.length)throw Error('WAITING_FOR_USER: 전용 Gmail과 허용 발신자를 설정하세요.');const ctx=await gmailContext(config,fetcher),messages=new Map();let pageToken='',pages=0;
// Snapshot IDs before removing AUTO_POST, so mailbox pagination cannot skip rows.
do{const query=new URLSearchParams({labelIds:ctx.source.id,maxResults:'100',q:'{'+config.gmailSenders.map(s=>'from:'+s).join(' ')+'}'});if(pageToken)query.set('pageToken',pageToken);const list=await google(ctx.base+'/messages?'+query,ctx.token,{},fetcher);for(const m of list.messages||[])messages.set(m.id,m);pageToken=list.nextPageToken||'';pages++}while(pageToken&&pages<10);
const counts={processed:0,done:0,review:0,error:0,labelErrors:0};const errors=[];
for(const message of messages.values()){let outcome='ERROR';try{const full=await google(ctx.base+'/messages/'+message.id+'?format=full',ctx.token,{},fetcher);if(!(full.labelIds||[]).includes(ctx.source.id))continue;const headers=Object.fromEntries((full.payload?.headers||[]).map(h=>[h.name.toLowerCase(),h.value]));const sender=(headers.from?.match(/<([^>]+)>/)?.[1]||headers.from||'').trim().toLowerCase();const result=await onMessage({providerId:full.id,messageId:headers['message-id']||'gmail:'+full.id,sender,subject:headers.subject||'',body:mailBody(full.payload||{}),viewMessageUrl:taskMessageLink(full.payload||{}),labels:[config.gmailLabel],mailbox:ctx.mailbox,receivedAt:Number(full.internalDate)||Date.now()});outcome=result?.status==='published'||result?.post_id?'DONE':result?.status==='rejected'||result?.status==='failed'?'ERROR':'REVIEW'}catch(e){if(/CHATGPT_LOGIN_REQUIRED/.test(String(e.message)))throw e;errors.push({id:message.id,error:String(e.message).slice(0,200)})}
try{await moveMail(ctx,message.id,outcome,fetcher);counts[outcome.toLowerCase()]++}catch(e){counts.labelErrors++;errors.push({id:message.id,error:'LABEL_UPDATE_FAILED: '+String(e.message).slice(0,200)});}counts.processed++}
if(counts.labelErrors)throw Error('GMAIL_LABEL_UPDATE_FAILED: '+counts.labelErrors+'; AUTO_POST 유지, 다음 polling에서 중복 게시 없이 재시도');return {...counts,mailboxVerified:true,pages,errors}}
export async function uploadYouTube(publication,file,{session=async()=>{},fetcher=fetch}={}){const {stat,open}=await import('node:fs/promises');const token=await accessToken('youtube',fetcher),size=(await stat(file)).size,metadata=JSON.parse(publication.metadata);const status={privacyStatus:publication.privacy==='public'?'public':publication.privacy==='unlisted'?'unlisted':'private',selfDeclaredMadeForKids:false};if(publication.privacy==='scheduled')status.publishAt=new Date(publication.scheduled_at).toISOString();let url=publication.upload_session,offset=0;
if(url){if(new URL(url).hostname!=='www.googleapis.com')throw Error('INVALID_UPLOAD_SESSION');const check=await fetcher(url,{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Length':'0','Content-Range':'bytes */'+size}});if(check.ok){const done=await check.json();return uploadResult(done,publication)}if(check.status===308)offset=Number(check.headers.get('range')?.match(/-(\d+)$/)?.[1]||-1)+1;else throw Error('UPLOAD_SESSION_EXPIRED: 새 업로드 전 YouTube 중복 여부를 확인하고 세션을 초기화하세요.')}
else{const r=await fetcher('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-Upload-Content-Type':'video/mp4','X-Upload-Content-Length':String(size)},body:JSON.stringify({snippet:{title:metadata.title,description:metadata.description,tags:metadata.tags,categoryId:'23'},status})});if(!r.ok)throw Error('YOUTUBE_INIT_'+r.status);url=r.headers.get('location');if(!url||new URL(url).hostname!=='www.googleapis.com')throw Error('INVALID_UPLOAD_SESSION');await session(url)}
const handle=await open(file,'r');try{while(offset<size){const length=Math.min(8*1024*1024,size-offset),buffer=Buffer.alloc(length);await handle.read(buffer,0,length,offset);let response;for(let attempt=0;attempt<3;attempt++){try{response=await fetcher(url,{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'video/mp4','Content-Length':String(length),'Content-Range':`bytes ${offset}-${offset+length-1}/${size}`},body:buffer});if(response.status<500)break}catch{if(attempt===2)throw Error('YOUTUBE_NETWORK_RETRY_REQUIRED')}await new Promise(r=>setTimeout(r,1000*(attempt+1)));const check=await fetcher(url,{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Length':'0','Content-Range':'bytes */'+size}});if(check.ok)return uploadResult(await check.json(),publication);if(check.status===308){const confirmed=Number(check.headers.get('range')?.match(/-(\d+)$/)?.[1]||-1)+1;if(confirmed!==offset){offset=confirmed;response=check;break}}}if(response?.ok)return uploadResult(await response.json(),publication);if(response?.status!==308)throw Error('YOUTUBE_UPLOAD_'+response?.status);offset=Number(response.headers.get('range')?.match(/-(\d+)$/)?.[1]||-1)+1;if(!offset)throw Error('UPLOAD_NO_PROGRESS')}}finally{await handle.close()}throw Error('UPLOAD_FINISH_UNCERTAIN: 저장된 세션으로 재시도하세요.')}
function uploadResult(video,p){if(!video.id)throw Error('UPLOAD_ID_MISSING');return {videoId:video.id,channelId:video.snippet?.channelId||'',status:video.status?.privacyStatus==='public'?'published':video.status?.privacyStatus==='unlisted'?'unlisted':p.privacy==='scheduled'&&video.status?.publishAt?'scheduled':'private'}}
export async function syncYouTube(publication,fetcher=fetch){if(!publication.external_id)throw Error('VIDEO_ID_MISSING');const token=await accessToken('youtube',fetcher),d=await google('https://www.googleapis.com/youtube/v3/videos?part=statistics,status&id='+encodeURIComponent(publication.external_id),token,{},fetcher),v=d.items?.[0];if(!v)throw Error('VIDEO_NOT_FOUND');return {views:Number(v.statistics.viewCount||0),likes:Number(v.statistics.likeCount||0),comments:Number(v.statistics.commentCount||0),status:v.status.privacyStatus==='public'?'published':v.status.publishAt?'scheduled':v.status.privacyStatus}}
