import {validateSource} from './validate-source.mjs';
import {readFile,writeFile,mkdir,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {scanSource,importMedia} from './adapters.mjs';import {renderJob} from './render.mjs';import {pollGmail,relabelGmail,uploadYouTube,syncYouTube} from './google.mjs';
try{process.loadEnvFile('.env.worker')}catch{}
const base=process.env.WORKER_SITE_URL?.replace(/\/$/,''),token=process.env.WORKER_TOKEN;if(!base||!token||token.length<32)throw Error('WORKER_SITE_URL과 32자 이상의 WORKER_TOKEN을 설정하세요.');const url=new URL(base);if(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname)))throw Error('HTTPS_REQUIRED');
const headers={Authorization:'Bearer '+token,...(process.env.SITES_DISPATCHER_TOKEN?{'OAI-Sites-Authorization':'Bearer '+process.env.SITES_DISPATCHER_TOKEN}:{})};
async function request(route,options){const r=await fetch(base+route,{...options,headers:{...headers,...options?.headers},redirect:'error',signal:AbortSignal.timeout(120000)});if(!r.ok){const body=await r.text();throw Error('WORKER_API_'+r.status+': '+body.slice(0,300))}return r}
const rpc=async data=>(await request('/api/worker',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})).json();
const capabilities={render:true,collect:true,gmail:!!process.env.GMAIL_REFRESH_TOKEN,youtube:!!process.env.YOUTUBE_REFRESH_TOKEN};let stop=false,connected=false;process.on('SIGINT',()=>{stop=true});process.on('SIGTERM',()=>{stop=true});
export async function runOnce(){const {task}=await rpc({action:'claim',workerId:process.env.WORKER_ID||os.hostname(),capabilities});if(!connected){console.log(JSON.stringify({status:'connected',workerId:process.env.WORKER_ID||os.hostname(),capabilities}));connected=true;}if(!task)return false;const auth={id:task.id,token:task.lease_token};let lost=false;const beat=setInterval(()=>rpc({...auth,action:'heartbeat'}).catch(()=>{lost=true}),30000);const call=async(action,data={})=>{if(lost)throw Error('LEASE_LOST');return rpc({...auth,action,...data})};const directory=path.resolve(process.env.WORKER_TEMP_DIR||'.worker-tmp',task.id);await mkdir(directory,{recursive:true});const download=async(key,file)=>{if(lost)throw Error('LEASE_LOST');const r=await request('/api/worker/files?key='+encodeURIComponent(key));await writeFile(file,Buffer.from(await r.arrayBuffer()))};const upload=async(data,type,kind)=>{if(lost)throw Error('LEASE_LOST');const query=new URLSearchParams({task:auth.id,token:auth.token,kind});return (await request('/api/worker/files?'+query,{method:'POST',headers:{'Content-Type':type,'Content-Length':String(data.length)},body:data})).json()};try{let result;switch(task.kind){case 'scan':result=task.payload.test?await validateSource(task.payload.source):await scanSource(task.payload.source);break;case 'publish':result=await importMedia(task.payload.candidate.detail,task.payload.source,async(data,type,kind)=>upload(data,type,kind));break;case 'render':{const r=await renderJob(task.payload,{directory,download,stage:(stage,progress,plan)=>call('stage',{stage,progress,plan}),split:partCount=>call('split',{partCount})});const saved=await upload(await readFile(r.file),'video/mp4','output');result={...r,key:saved.key};delete result.file;break}case 'gmail':result=await pollGmail(task.config,message=>call('mail',{message}));break;case 'gmailLabel':if(task.config.gmailMailbox.toLowerCase()!==String(task.payload.mailbox).toLowerCase())throw Error('WAITING_FOR_USER: Gmail mailbox changed');result=await relabelGmail(task.config,task.payload.providerId,task.payload.outcome);break;case 'upload':{const file=path.join(directory,'upload.mp4');await download(task.payload.output.storage_key,file);result=await uploadYouTube(task.payload.publication,file,{session:url=>call('uploadSession',{url})});break}case 'sync':result=await syncYouTube(task.payload.publication);break;default:throw Error('UNKNOWN_TASK_KIND')}await call('complete',{result});console.log(JSON.stringify({task:task.id,kind:task.kind,status:'completed'}))}catch(e){const error=String(e.message).slice(0,1000);console.error(JSON.stringify({task:task.id,kind:task.kind,error}));await rpc({...auth,action:'fail',error,blocked:/BLOCKED|WAITING_FOR_USER|SPLIT_REQUIRED/.test(error)}).catch(()=>{})}finally{clearInterval(beat);await rm(directory,{recursive:true,force:true})}return true}
do{try{const worked=await runOnce();if(process.argv.includes('--once'))break;if(!worked)await new Promise(r=>setTimeout(r,15000))}catch(e){console.error(e.message);if(process.argv.includes('--once'))process.exitCode=1;else await new Promise(r=>setTimeout(r,15000))}}while(!stop&&!process.argv.includes('--once'));
