import https from 'node:https';import {lookup} from 'node:dns/promises';import {isIP} from 'node:net';
export function publicIP(ip){if(isIP(ip)===4){const [a,b]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&(b===168||b===0||b===2))||(a===100&&b>=64&&b<=127)||(a===198&&(b===18||b===19||b===51))||(a===203&&b===0))}if(isIP(ip)===6)return /^[23][0-9a-f]{3}:/i.test(ip)&&!/^2001:(db8|0):/i.test(ip);return false}
export async function fetchPublic(value,{max=2*1024*1024,hosts=[],redirects=4,method='GET',body,referer,beforeRedirect,contentType='application/x-www-form-urlencoded'}={}){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port&&u.port!=='443'||isIP(u.hostname)||!u.hostname.includes('.'))throw Error('UNSAFE_URL');if(hosts.length&&!hosts.some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))throw Error('MEDIA_HOST_NOT_ALLOWED');const ips=await lookup(u.hostname,{all:true});if(!ips.length||ips.some(x=>!publicIP(x.address)))throw Error('PRIVATE_NETWORK_BLOCKED');
const result=await new Promise((resolve,reject)=>{const req=https.request(u,{method,headers:{...(referer?{Referer:referer}:{}),...(body?{'Content-Type':contentType,'Content-Length':Buffer.byteLength(body)}:{}),...{'User-Agent':'SecretAgitBot/1.0 (community content preview)','Accept':'text/html,application/json,image/*,video/*;q=.8'}},lookup:(_host,options,cb)=>options.all?cb(null,ips):cb(null,ips[0].address,ips[0].family)},res=>{const status=res.statusCode||0;if(status>=300&&status<400){res.resume();resolve({status,location:res.headers.location,bytes:Buffer.alloc(0),type:''});return}if([401,403,429].includes(status)){res.resume();reject(Error('BLOCKED: HTTP '+status));return}if(status!==200){res.resume();reject(Error('HTTP '+status));return}if(Number(res.headers['content-length'])>max){res.destroy();reject(Error('RESPONSE_TOO_LARGE'));return}const chunks=[];let size=0;res.on('data',b=>{size+=b.length;if(size>max){res.destroy();reject(Error('RESPONSE_TOO_LARGE'))}else chunks.push(b)});res.on('end',()=>resolve({status,bytes:Buffer.concat(chunks),type:String(res.headers['content-type']||'')}));res.on('error',reject)});req.setTimeout(15000,()=>req.destroy(Error('FETCH_TIMEOUT')));req.on('error',reject);req.end(body)});
if(result.location){if(method!=='GET')throw Error('POST_REDIRECT_BLOCKED');if(!redirects)throw Error('REDIRECT_LIMIT');const next=new URL(result.location,u).href;if(beforeRedirect)await beforeRedirect(next);return fetchPublic(next,{max,hosts,redirects:redirects-1,referer,beforeRedirect})}return {...result,url:u.href}}
export function decodeHTML(bytes,type=''){const encoding=type.match(/charset=([\w-]+)/i)?.[1]||bytes.subarray(0,4096).toString().match(/charset=["']?([\w-]+)/i)?.[1]||'utf-8';try{return new TextDecoder(encoding).decode(bytes)}catch{return bytes.toString('utf8')}}

export function robotsPolicy(text,url,agent='secretagitbot'){
 const groups=[];let group={agents:[],rules:[],delay:0},hasRules=false;
 for(const raw of text.split(/\r?\n/)){const line=raw.replace(/#.*/,'').trim(),i=line.indexOf(':');if(i<0)continue;const key=line.slice(0,i).toLowerCase(),value=line.slice(i+1).trim();if(key==='user-agent'){if(hasRules){groups.push(group);group={agents:[],rules:[],delay:0};hasRules=false}group.agents.push(value.toLowerCase())}else if(group.agents.length&&['allow','disallow','crawl-delay'].includes(key)){hasRules=true;if(key==='crawl-delay')group.delay=Math.max(0,Math.min(60,Number(value)||0));else if(value)group.rules.push({allow:key==='allow',pattern:value})}}groups.push(group);
 const explicit=groups.filter(g=>g.agents.some(a=>a!=='*'&&agent.toLowerCase().includes(a))),chosen=explicit.length?explicit:groups.filter(g=>g.agents.includes('*'));const target=new URL(url).pathname+new URL(url).search;let match=null;
 for(const g of chosen)for(const rule of g.rules){const end=rule.pattern.endsWith('$');const pattern=(end?rule.pattern.slice(0,-1):rule.pattern).split('*').map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('.*');if(new RegExp('^'+pattern+(end?'$':'')).test(target)){const length=rule.pattern.replace(/[*$]/g,'').length;if(!match||length>match.length||length===match.length&&rule.allow)match={...rule,length}}}return {allowed:match?.allow??true,delay:Math.max(0,...chosen.map(g=>g.delay)),matched:match?.pattern||''};
}
const robotCache=new Map(),lastRequest=new Map();
export async function getRobots(url){const u=new URL(url);let cached=robotCache.get(u.origin);if(!cached||Date.now()-cached.at>3600000){let text='';try{const r=await fetchPublic(u.origin+'/robots.txt',{max:256000,hosts:[u.hostname.replace(/^www\./,'')]});text=r.bytes.toString()}catch(e){if(!String(e).includes('HTTP 404'))throw e}cached={text,at:Date.now()};robotCache.set(u.origin,cached)}return robotsPolicy(cached.text,url)}
export async function robotsAllowed(url){return (await getRobots(url)).allowed}
export async function fetchPage(url,options={}){const policy=await getRobots(url);if(!policy.allowed)throw Error('BLOCKED: robots.txt '+policy.matched);const origin=new URL(url).origin,wait=Math.max(0,(lastRequest.get(origin)||0)+Math.max(700,policy.delay*1000)-Date.now());if(wait)await new Promise(r=>setTimeout(r,wait));lastRequest.set(origin,Date.now());const r=await fetchPublic(url,{...options,hosts:options.hosts||[new URL(url).hostname.replace(/^www\./,'')],beforeRedirect:async next=>{if(!await robotsAllowed(next))throw Error('BLOCKED: redirect robots.txt')}});if(r.url!==url&&!await robotsAllowed(r.url))throw Error('BLOCKED: redirect robots.txt');return r}
