export const FPS=30;
export function easeScroll(frame,total,distance){const hold=Math.min(30,total*.15);const p=Math.max(0,Math.min(1,(frame-hold)/Math.max(1,total-hold*2)));return -distance*(p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2)}
export function buildPlan(posts,settings,brand={name:'미정',url:''}){const scenes=[],warnings=[];let total=0;const add=(type,seconds,payload={})=>{const frames=Math.max(1,Math.round(seconds*FPS));scenes.push({type,from:total,frames,payload});total+=frames};if(settings.intro)add('intro',1.5,{text:brand.name});
for(const [index,p]of posts.slice(0,settings.maxPosts).entries()){if(index)add('transition',.6,{text:'다음 이야기'});add('post_title',Math.max(1.8,p.title.length/10),{text:p.title});
for(const b of p.blocks){if(b.type==='text'){const parts=b.text.match(/[\s\S]{1,500}/g)||[];for(const text of parts)add('post_body_scroll',Math.max(2,text.length/(10*settings.speed)+1),{text})}
else if(b.type==='image'||b.type==='video'){const asset=p.media.find(m=>m.id===b.id);if(!asset?.src){warnings.push('누락 미디어 제외: '+b.id);continue}const gif=asset.type==='image/gif';const duration=b.type==='video'?Math.max(.5,asset.duration||3):gif?Math.min(8,asset.duration||4):3;add(b.type==='video'?'video_play':gif?'gif_play':'image_hold',duration,{src:asset.src,hasAudio:!!asset.hasAudio,originalVolume:settings.originalVolume})}
else if(b.type==='youtube')warnings.push('유튜브 임베드는 다운로드/렌더 제외')}
if(settings.includeComments){for(const c of (p.comments||[]).slice(0,settings.maxComments))add('comments',Math.max(2,c.body.length/(11*settings.speed)),{text:c.body})}}
if(settings.outro)add('outro',2,{text:settings.cta?brand.name+'에서 더 보기':brand.name});
let targetGap=Math.max(0,settings.targetDuration*FPS-total);for(const scene of scenes){if(['image_hold','gif_play'].includes(scene.type)&&targetGap>0){const extra=Math.min(targetGap,Math.max(0,6*FPS-scene.frames));scene.frames+=extra;targetGap-=extra;total+=extra}}let timeline=0;for(const scene of scenes){scene.from=timeline;timeline+=scene.frames}
if(total/FPS>settings.maxDuration){const ratio=Math.max(1/1.3,settings.maxDuration/(total/FPS));total=0;for(const scene of scenes){if(['post_title','post_body_scroll','comments'].includes(scene.type))scene.frames=Math.ceil(scene.frames*ratio);scene.from=total;total+=scene.frames}}
if(total/FPS<settings.minDuration){const last=scenes.at(-1);if(last){last.frames+=Math.ceil(settings.minDuration*FPS-total);total=settings.minDuration*FPS}}
const parts=[];let part=[],frames=0;const max=settings.maxDuration*FPS;for(const s of scenes){let remaining=s.frames,offset=0;while(remaining>0){const take=Math.min(remaining,max-frames);part.push({...s,from:frames,frames:take,payload:{...s.payload,startFrame:offset,totalFrames:s.frames}});frames+=take;remaining-=take;offset+=take;if(frames>=max){parts.push({scenes:part,durationFrames:frames});part=[];frames=0}}}if(part.length)parts.push({scenes:part,durationFrames:frames});
if(total/FPS<settings.minDuration)warnings.push('최소 권장 길이 미만');if(parts.length>1)warnings.push('분할 권장: '+parts.length+'편');const chosen=Number.isInteger(settings.partIndex)?parts[settings.partIndex]:parts[0];return {...chosen,fullDurationFrames:total,partCount:parts.length,parts,settings,brand,warnings,requiresSplit:parts.length>1&&!settings.autoSplit&&!Number.isInteger(settings.partIndex),audioMode:settings.audioPolicy,lastScene:chosen?.scenes.at(-1)?.type}}
