export const FPS=30;
// Bound both line width and explicit line breaks so text never leaves the card.
export function textPages(text,columns=19,rows=11){const lines=[];for(const line of String(text||'').split('\n')){const chars=Array.from(line);if(!chars.length)lines.push('');while(chars.length)lines.push(chars.splice(0,columns).join(''))}const pages=[];while(lines.length)pages.push(lines.splice(0,rows).join('\n'));return pages.filter(x=>x.trim())}
export function easeScroll(frame,total,distance){const hold=Math.min(30,total*.15);const p=Math.max(0,Math.min(1,(frame-hold)/Math.max(1,total-hold*2)));return -distance*(p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2)}
export function buildPlan(posts,settings,brand={}){brand={...brand,name:'스르륵',url:'https://www.ssrrr.net'};const selectedPosts=posts.slice(0,settings.maxPosts);const firstBlocks=selectedPosts[0]?.blocks||[];const compactSingleImage=selectedPosts.length===1&&firstBlocks.filter(b=>b.type==='image').length===1&&!firstBlocks.some(b=>b.type==='video'||b.type==='youtube'||(b.type==='text'&&b.text?.trim()));const scenes=[],warnings=[];let total=0;const add=(type,seconds,payload={})=>{const frames=Math.max(1,Math.round(seconds*FPS));scenes.push({type,from:total,frames,payload});total+=frames};
for(const [index,p]of selectedPosts.entries()){const title=String(p.title||'').trim()||'오늘의 스르륵';if(index)add('transition',.6,{text:'다음 이야기'});const cover=p.blocks.map(b=>p.media.find(m=>m.id===b.id&&m.type.startsWith('image/')&&m.type!=='image/gif'&&m.src)).find(Boolean);if(settings.intro)add('feed_open',2,{text:title,src:cover?.src});add('post_title',Math.max(3,title.length/10),{text:title,src:cover?.src});
for(const b of p.blocks){if(b.type==='text'){const parts=textPages(b.text);for(const text of parts)add('post_body_scroll',Math.max(2,text.length/(10*settings.speed)+1),{text})}
else if(b.type==='image'||b.type==='video'){const asset=p.media.find(m=>m.id===b.id);if(!asset?.src){warnings.push('누락 미디어 제외: '+b.id);continue}const gif=asset.type==='image/gif';const duration=b.type==='video'?Math.max(.5,asset.duration||3):gif?Math.min(8,asset.duration||4):3;add(b.type==='video'?'video_play':gif?'gif_play':'image_hold',duration,{src:asset.src,hasAudio:!!asset.hasAudio,originalVolume:settings.originalVolume})}
else if(b.type==='youtube')warnings.push('유튜브 임베드는 다운로드/렌더 제외')}
if(settings.includeComments){for(const c of (p.comments||[]).slice(0,settings.maxComments))for(const text of textPages(c.body,19,10))add('comments',Math.max(2,text.length/(11*settings.speed)),{text,reaction:/[ㅋㅎ]{2,}/.exec(text)?.[0]?.slice(0,8)})}}
if(settings.outro)add('outro',3,{text:settings.cta?'이 글의 다음 이야기는?\n스르륵에서 같이 봐요':brand.name});
const targetDuration=compactSingleImage?Math.min(settings.targetDuration,12):settings.targetDuration;const maxImageSeconds=compactSingleImage?4:6;let targetGap=Math.max(0,targetDuration*FPS-total);for(const scene of scenes){if(['image_hold','gif_play'].includes(scene.type)&&targetGap>0){const extra=Math.min(targetGap,Math.max(0,maxImageSeconds*FPS-scene.frames));scene.frames+=extra;targetGap-=extra;total+=extra}}let timeline=0;for(const scene of scenes){scene.from=timeline;timeline+=scene.frames}
if(total/FPS>settings.maxDuration){const ratio=Math.max(1/1.3,settings.maxDuration/(total/FPS));total=0;for(const scene of scenes){if(['post_title','post_body_scroll','comments'].includes(scene.type))scene.frames=Math.ceil(scene.frames*ratio);scene.from=total;total+=scene.frames}}
const parts=[];let part=[],frames=0;const max=settings.maxDuration*FPS;for(const s of scenes){let remaining=s.frames,offset=0;while(remaining>0){const take=Math.min(remaining,max-frames);part.push({...s,from:frames,frames:take,payload:{...s.payload,startFrame:offset,totalFrames:s.frames}});frames+=take;remaining-=take;offset+=take;if(frames>=max){parts.push({scenes:part,durationFrames:frames});part=[];frames=0}}}if(part.length)parts.push({scenes:part,durationFrames:frames});
if(total/FPS<settings.minDuration&&!compactSingleImage)warnings.push('최소 권장 길이 미만');if(parts.length>1)warnings.push('분할 권장: '+parts.length+'편');const chosen=Number.isInteger(settings.partIndex)?parts[settings.partIndex]:parts[0];return {...chosen,fullDurationFrames:total,partCount:parts.length,parts,settings,brand,warnings,requiresSplit:parts.length>1&&!settings.autoSplit&&!Number.isInteger(settings.partIndex),audioMode:settings.audioPolicy,lastScene:chosen?.scenes.at(-1)?.type}}
