import {wrap,db,json,HttpError,cleanText} from '@/lib/server';
import {settings,admin,validateSettings} from '@/lib/settings';
export const GET=wrap(async req=>{await admin();const query=(new URL(req.url).searchParams.get('q')||'').slice(0,50);const offset=Math.max(0,Math.min(10000,Number(new URL(req.url).searchParams.get('offset'))||0));const [s,members,stats,logs]=await Promise.all([settings(),db().prepare('SELECT owner,nickname,points,created_at FROM members WHERE nickname LIKE ? ORDER BY created_at DESC LIMIT 31 OFFSET ?').bind('%'+query+'%',offset).all(),db().prepare('SELECT (SELECT COUNT(*) FROM members) members,(SELECT COUNT(*) FROM posts WHERE hidden=0) posts,(SELECT COUNT(*) FROM purchases) downloads,(SELECT COALESCE(SUM(cost),0) FROM purchases) spent').first(),db().prepare('SELECT id,action,created_at FROM audit ORDER BY created_at DESC LIMIT 20').all()]);return Response.json({...s,members:members.results.slice(0,30),more:members.results.length>30,stats,logs:logs.results},{headers:{'Cache-Control':'no-store'}})});
export const POST=wrap(async req=>{const u=await admin(req);const d=await json(req);if(d.action==='settings'){const value=validateSettings(d.settings);if(!Number.isSafeInteger(d.revision)||d.revision<0)throw new HttpError(400,'설정 버전을 확인해 주세요.');const stm=db().prepare("INSERT INTO settings(id,value,revision) SELECT 'community',?,1 WHERE ?=0 ON CONFLICT(id) DO UPDATE SET value=excluded.value,revision=revision+1 WHERE revision=?").bind(JSON.stringify(value),d.revision,d.revision); // Existing-row updates use a separate statement to avoid SELECT filtering.
const update=d.revision===0?stm:db().prepare("UPDATE settings SET value=?,revision=revision+1 WHERE id='community' AND revision=?").bind(JSON.stringify(value),d.revision);
const r=await update.run();if(!r.meta.changes)throw new HttpError(409,'다른 창에서 설정이 변경되었습니다. 새로 불러온 후 다시 저장해 주세요.');await db().prepare('INSERT INTO audit(id,actor,action,created_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),u.userId,'운영 설정 변경: '+JSON.stringify(value),Date.now()).run();return Response.json(await settings())}
if(d.action==='grant'){const owner=cleanText(d.owner,200),reason=cleanText(d.reason,150),requestId=cleanText(d.requestId,80);if(!/^[a-f0-9-]{36}$/.test(requestId)||!Number.isSafeInteger(d.amount)||d.amount<1||d.amount>100000)throw new HttpError(400,'지급 포인트는 1~100,000P로 입력해 주세요.');if(!await db().prepare('SELECT owner FROM members WHERE owner=?').bind(owner).first())throw new HttpError(404,'회원이 없습니다.');await db().prepare('INSERT INTO grants(id,owner,amount,reason,actor,created_at) SELECT ?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM grants WHERE id=?)').bind(requestId,owner,d.amount,reason,u.userId,Date.now(),requestId).run();return Response.json({ok:true})}
throw new HttpError(400,'지원하지 않는 요청입니다.')});

